// data.js — Roadmap Engenharia da Computacao v3
// Ordem LOGICA: cada area depende da anterior
// w=what, s=search terms, d=detail
const ROADMAP=[
{id:"beginner",name:"\u{1F7E2} INICIANTE",css:"green",time:"~6-12 meses",desc:"Fundacao solida. Na ordem \u2014 cada area depende da anterior.",areas:[
{name:"\u{1F9E0} Fundamentos de Computacao",topics:[
{name:"Como Computadores Funcionam",books:["Code: The Hidden Language \u2014 Charles Petzold","Organizacao Estruturada de Computadores \u2014 Tanenbaum","But How Do It Know? \u2014 J. Clark Scott"],items:[
{w:"O que e um computador? Hardware vs Software",s:"what is a computer hardware software, o que e computador hardware software, computer basics",d:"Hardware: parte fisica (teclado, tela, placa). Software: programas (SO, apps, jogos). Hardware sem software e uma caixa cara. Software sem hardware nao roda."},
{w:"Arquitetura: CPU, RAM, Disco, Barramento, Cache",s:"computer architecture basics CPU RAM, arquitetura computadores basico",d:"CPU processa. RAM = memoria rapida temporaria. Disco = permanente. Barramento conecta tudo. Cache L1/L2/L3 dentro da CPU. Hierarquia: registradores > cache > RAM > SSD > HDD."},
{w:"Sistema Binario, Hexadecimal, Representacao de Dados",s:"binary hexadecimal number systems, sistema binario hexadecimal computacao",d:"Binario (base 2): 1010=10. Hex (base 16): 0xFF=255. ASCII: A=65. UTF-8 suporta emojis. Imagens: pixels RGB. Pratique conversoes decimal-binario-hex."},
{w:"Ciclo Fetch-Decode-Execute e Clock",s:"fetch decode execute cycle, ciclo instrucao CPU, how CPU processes instructions",d:"CPU: busca instrucao da memoria, decodifica, executa, repete bilhoes de vezes/segundo. Clock (GHz) = ciclos/segundo. 3GHz = 3 bilhoes de ciclos/s."},
{w:"Memoria Volatil vs Nao-Volatil, Hierarquia de Memoria",s:"volatile non-volatile memory, RAM ROM SSD difference, memory hierarchy",d:"Volatil (RAM): perde dados ao desligar. Nao-volatil (SSD/HDD): mantem. Registradores > Cache > RAM > SSD > HDD. Mais rapido = mais caro = menor."},
{w:"GPU, Placa-mae, Fonte, Perifericos",s:"GPU graphics card, motherboard components, computer peripherals explained",d:"GPU: processamento paralelo (graficos, IA). Placa-mae: conecta tudo. Fonte: energia. USB, HDMI, Bluetooth, WiFi."},
{w:"Como software e executado: compilacao vs interpretacao",s:"compiled vs interpreted languages, compilacao interpretacao, how code runs",d:"Compilado: C/C++ (traduz tudo antes). Interpretado: Python/JS (traduz linha a linha). JIT: Java/C# (mistura). Mais perto do hardware = mais rapido."}]},
{name:"Pensamento Computacional",books:["Think Like a Programmer \u2014 V. Anton Spraul","Computational Thinking \u2014 Denning & Tedre","Bem-vindo a Computacao \u2014 Manzano & Oliveira"],items:[
{w:"Decomposicao de Problemas",s:"problem decomposition computer science, decomposicao problemas computacao, CS Unplugged",d:"Quebre problemas grandes em menores. Fazer bolo = comprar + pre-aquecer + misturar + assar. Na programacao cada pedaco vira funcao. Pratique com CS Unplugged."},
{w:"Reconhecimento de Padroes e Abstracao",s:"pattern recognition abstraction CS, reconhecimento padroes abstracao, computational thinking",d:"Padroes: ordenar cartas e nomes usa mesma logica. Abstracao: focar no essencial (mapa = abstracao da cidade). Programar e criar camadas de abstracao."},
{w:"Algoritmos, Pseudocodigo e Fluxogramas",s:"algorithm pseudocode flowchart beginners, pseudocodigo fluxograma, how to write algorithms",d:"Algoritmo = passos finitos. Pseudocodigo: SE nota>=7 ENTAO Aprovado. Fluxograma: retangulo=processo, losango=decisao. Escreva algoritmo ANTES de programar. Use draw.io."},
{w:"Complexidade intuitiva: por que alguns problemas sao mais dificeis",s:"algorithm complexity intuition, por que algoritmos sao lentos, computational complexity basics",d:"Buscar em lista: olhar 1 por 1 (lento) vs dividir no meio (rapido). Ordenar: N comparacoes vs N*N. Intuicao agora, formalizacao depois em Big O."}]},
{name:"Como a Internet Funciona",books:["Computer Networking: A Top-Down Approach \u2014 Kurose & Ross","How the Internet Works \u2014 Preston Gralla","Redes de Computadores \u2014 Tanenbaum"],items:[
{w:"O que e internet: ISP, roteadores, pacotes, IP",s:"how internet works basics, como funciona internet, internet ISP packets routing",d:"Internet = rede de redes. Seu PC > roteador > ISP > backbone > servidor. Dados viajam em pacotes. IP: endereco do dispositivo (ex: 192.168.1.1)."},
{w:"DNS, HTTP/HTTPS, cliente-servidor, URLs",s:"DNS explained, HTTP HTTPS client server, how websites work URL",d:"Voce digita google.com > DNS traduz pra IP > navegador envia HTTP request > servidor responde HTML. HTTPS: criptografado (cadeado). URL: protocolo://dominio/caminho."},
{w:"WiFi, Ethernet, Bluetooth, enderecos MAC e IP",s:"WiFi Ethernet Bluetooth explained, MAC address vs IP address, network basics",d:"WiFi: sem fio (802.11). Ethernet: cabo (mais estavel). Bluetooth: curto alcance. MAC: ID fisico da placa. IP: endereco logico na rede."},
{w:"O que acontece quando voce acessa um site (passo a passo)",s:"what happens when you type URL, DNS lookup TCP handshake, web request lifecycle",d:"Digitar URL > DNS resolve IP > TCP handshake (3-way) > HTTP GET request > servidor processa > envia HTML/CSS/JS > navegador renderiza. Tudo em milissegundos."}]}]},
{name:"\u{1F4BB} Sistemas Operacionais & Terminal",topics:[
{name:"Conceitos de SO",books:["Operating Systems: Three Easy Pieces \u2014 Arpaci-Dusseau (gratuito)","How Linux Works \u2014 Brian Ward","Sistemas Operacionais Modernos \u2014 Tanenbaum"],items:[
{w:"O que e um SO: kernel, processos, filesystem, memoria",s:"what is operating system kernel, sistema operacional fundamentals, OS concepts",d:"SO gerencia hardware. Kernel = nucleo. Processo = programa rodando. Filesystem = organizacao de arquivos. O SO decide quem usa CPU e RAM."},
{w:"Tipos de SO: Windows, Linux, macOS. Distribuicoes Linux",s:"linux distributions comparison, tipos SO windows linux macOS, ubuntu vs mint vs fedora",d:"Windows: mais usado desktop. Linux: servidores, dev, gratuito. macOS: Apple. Distros Linux: Ubuntu(iniciante), Mint(Windows-like), Fedora(bleeding edge), Arch(avancado)."},
{w:"Processos vs Threads, multitarefa, escalonamento",s:"processes vs threads OS, multitasking scheduling, processos threads sistema operacional",d:"Processo: programa rodando com sua memoria. Thread: sub-processo (compartilha memoria). Multitarefa: SO alterna rapido. Escalonador: decide quem roda."},
{w:"Gerenciamento de memoria: RAM, swap, memoria virtual",s:"memory management OS, virtual memory swap, gerenciamento memoria sistema operacional",d:"RAM dividida entre processos. Swap: usa disco quando RAM enche (lento). Memoria virtual: cada processo acha que tem toda RAM pra si."}]},
{name:"Linux e Linha de Comando",books:["The Linux Command Line \u2014 William Shotts","How Linux Works \u2014 Brian Ward","Guia Foca Linux \u2014 Gleydson da Silva (gratuito)"],items:[
{w:"Instalar Linux: dual boot, VM ou WSL2",s:"install ubuntu dual boot, linux virtual machine VirtualBox, WSL2 windows",d:"VM (VirtualBox) = mais seguro pra comecar. Dual boot = melhor performance. WSL2 = Linux dentro do Windows. Ubuntu ou Mint pra iniciantes."},
{w:"Filesystem Linux: /, /home, /etc, /var, /tmp, /usr, /bin",s:"linux filesystem hierarchy, estrutura diretorios linux, linux directory structure",d:"/ = raiz. /home = seus arquivos. /etc = configuracoes. /var = logs. /tmp = temporarios. /usr = programas. Tudo e arquivo no Linux, ate dispositivos!"},
{w:"Comandos essenciais: ls, cd, mkdir, cp, mv, rm, cat, grep, find, chmod, sudo",s:"linux terminal commands beginners, comandos linux essenciais terminal, linux CLI tutorial",d:"ls (listar), cd (navegar), pwd (onde estou), mkdir (criar pasta), cp/mv/rm, cat/less/head/tail, grep (buscar texto), find (buscar arquivo), chmod (permissoes), sudo (admin)."},
{w:"Editores no terminal: nano (facil) e vim (poderoso)",s:"nano editor tutorial, vim basics tutorial, linux text editors terminal",d:"nano: Ctrl+O salvar, Ctrl+X sair. Simples. vim: i(inserir), Esc(sair modo), :wq(salvar+sair), :q!(sair sem salvar). Curva ingreme mas vale aprender o basico."},
{w:"Pacotes: apt, snap, flatpak. Repositorios e PPAs",s:"apt package manager ubuntu, linux package management, snap flatpak comparison",d:"apt update/upgrade/install/remove. snap/flatpak: apps empacotados. PPA: repositorios extras. Sempre apt update antes de apt install."},
{w:"Processos: ps, top/htop, kill, systemctl, cron",s:"linux processes ps top kill, systemctl services, crontab scheduled tasks",d:"ps aux lista. top/htop monitora. kill PID. systemctl start/stop/enable servicos. cron: agendar tarefas (crontab -e)."},
{w:"Permissoes rwx, usuarios, grupos, chown",s:"linux permissions rwx chmod chown, linux users groups, file permissions",d:"rwx = read/write/execute pra owner/group/others. chmod 755. chown user:group arquivo. Grupos: compartilhar acesso."},
{w:"Variaveis de ambiente, PATH, .bashrc/.zshrc",s:"environment variables PATH linux, bashrc zshrc config, linux shell configuration",d:"export VAR=valor. $PATH diz onde achar executaveis. ~/.bashrc carrega ao abrir terminal. Aliases: alias ll='ls -la'."},
{w:"Shell scripting: bash, pipes, redirecionamento, condicoes",s:"bash scripting tutorial, linux pipes redirection, shell script if for while",d:"#!/bin/bash. chmod +x script.sh. Pipes: ls | grep .py. > (sobrescreve) >> (adiciona). if/then/fi. for f in *.txt; do ... done."},
{w:"SSH, SCP, chaves publicas/privadas",s:"SSH tutorial beginners, SSH key pair, SCP file transfer linux",d:"ssh user@servidor. ssh-keygen -t ed25519. Copiar chave: ssh-copy-id. SCP: scp arquivo user@host:/caminho. Mais seguro que senha."}]}]},
{name:"\u{1F40D} Logica de Programacao com Python",topics:[
{name:"Setup e Primeiros Passos",books:["Python Crash Course \u2014 Eric Matthes","Automate the Boring Stuff \u2014 Al Sweigart (gratuito)","Introducao a Programacao com Python \u2014 Nilo Ney Menezes"],items:[
{w:"Instalar Python 3.12+ e configurar VS Code",s:"install python 3.12 VS Code setup 2025, configurar python vscode",d:"python.org/downloads. Windows: marque Add to PATH. Linux: sudo apt install python3. VS Code + extensao Python (Microsoft). Teste: python3 -c \"print('Oi')\""},
{w:"REPL interativo e Jupyter Notebook",s:"python REPL interactive, jupyter notebook tutorial, google colab python",d:"python3 no terminal = modo interativo (>>>). Jupyter: pip install notebook. Google Colab: online gratis."},
{w:"Variaveis, tipos (int, float, str, bool, None), type()",s:"python variables data types, variaveis tipos python, python type function",d:"nome='Kaio'(str), idade=20(int), pi=3.14(float), ativo=True(bool), vazio=None. type(x) mostra tipo. Tipagem dinamica."},
{w:"Operadores: aritmeticos, comparacao, logicos, atribuicao",s:"python operators arithmetic comparison logical, operadores python, python == != and or not",d:"+ - * / // % **. == != > < >= <=. and or not. = += -= *=. CUIDADO: = vs ==."},
{w:"input(), print(), f-strings",s:"python input print f-string, entrada saida python, python string formatting",d:"print(f'Tenho {idade} anos'). input() retorna STRING, converta: int(input('Num: ')). f'{preco:.2f}' = 2 decimais."}]},
{name:"Strings",books:["Python Crash Course \u2014 Eric Matthes","Learning Python \u2014 Mark Lutz","Automate the Boring Stuff \u2014 Al Sweigart"],items:[
{w:"Indexacao, fatiamento: s[0], s[2:5], s[::-1]",s:"python string slicing indexing, fatiamento strings python, python slice",d:"s[0]=primeiro, s[-1]=ultimo, s[2:5]=2 ao 4, s[::-1]=invertida. Indice comeca em 0! Strings sao IMUTAVEIS."},
{w:"Metodos: upper, lower, strip, split, join, replace, find, count, in",s:"python string methods, metodos string python, python split join replace",d:".upper() .lower() .strip() .split(',') .join() .replace() .find() .count(). 'py' in 'python'=True."},
{w:"F-strings avancadas e regex basico (modulo re)",s:"python f-string advanced, python regex re module, expressoes regulares python",d:"f'{val:.2f}' f'{val:,}'. import re. re.findall(r'\\d+', texto). Padroes: \\d \\w \\s . + * ?."}]},
{name:"Controle de Fluxo",books:["Python Crash Course \u2014 Eric Matthes","Think Python \u2014 Allen Downey (gratuito)","Introducao a Programacao com Python \u2014 Nilo Ney Menezes"],items:[
{w:"if / elif / else com indentacao",s:"python if elif else tutorial, condicionais python, python conditional statements",d:"if cond: (4 espacos). elif: (senao se). else: (senao). Ternario: x='par' if n%2==0 else 'impar'. match-case (3.10+)."},
{w:"for: range(), enumerate(), zip()",s:"python for loop range enumerate zip, loop for python, python iterate",d:"for i in range(10): (0 a 9). enumerate(): indice+valor. zip(): 2 listas em paralelo. range(start,stop,step)."},
{w:"while, break, continue, else em loops",s:"python while break continue, loop while python, python loop else",d:"while cond: repete. break: sai. continue: pula. for...else: roda se NAO houve break. Cuidado loop infinito!"},
{w:"Loops aninhados e padroes comuns",s:"python nested loops patterns, loops aninhados python, python loop exercises",d:"for i in range(3): for j in range(3): = O(n2). Exercicio: piramide de *, tabuada, pattern printing."}]},
{name:"Estruturas de Dados Nativas",books:["Python Crash Course \u2014 Eric Matthes","Python Fluente \u2014 Luciano Ramalho","Data Structures in Python \u2014 Goodrich et al."],items:[
{w:"Listas: criacao, indexacao, metodos (append, pop, sort...)",s:"python lists tutorial, listas python metodos, python list operations",d:"nums=[1,2,3]. .append .insert .pop .remove .sort .reverse .index len(). Fatiamento. Mutaveis."},
{w:"Tuplas: imutaveis, unpacking, namedtuple",s:"python tuples unpacking, tuplas python, python namedtuple",d:"t=(1,2,3). Imutavel. a,b,c=t. Usar pra coordenadas, retornos multiplos, chaves de dict."},
{w:"Dicionarios: chave-valor, metodos, iteracao",s:"python dict tutorial, dicionarios python, python dictionary methods",d:"d={'nome':'Kaio'}. d.get('x','default'). .keys() .values() .items(). for k,v in d.items():. O(1)."},
{w:"Sets: sem duplicatas, operacoes de conjunto",s:"python sets operations, sets python, python set union intersection",d:"s={1,2,3}. | (uniao) & (intersecao) - (diferenca). x in s = O(1)."},
{w:"Comprehensions e desempacotamento (*)",s:"python comprehensions, list dict set comprehension, python unpacking star",d:"[x**2 for x in range(10)]. {k:v for ...}. a,*rest=[1,2,3,4]. a,b=b,a."}]},
{name:"Funcoes",books:["Clean Code \u2014 Robert Martin","Think Python \u2014 Allen Downey (gratuito)","Effective Python \u2014 Brett Slatkin"],items:[
{w:"def, parametros, return, docstrings",s:"python functions def return, funcoes python parametros, python docstrings",d:"def media(notas): '''Calcula media.''' return sum(notas)/len(notas). Uma funcao faz UMA coisa."},
{w:"Default, *args, **kwargs, escopo LEGB",s:"python args kwargs default, python scope LEGB, python function arguments",d:"def f(x,y=10). *args: tupla. **kwargs: dict. LEGB: Local>Enclosing>Global>Built-in."},
{w:"Lambda, funcoes como objetos, decorators",s:"python lambda decorators, python first class functions, python decorator tutorial",d:"lambda x: x*2. Funcoes sao objetos. @decorator = wrapper. @property @staticmethod."},
{w:"Recursao: caso base, caso recursivo",s:"python recursion tutorial, recursao python, recursive functions factorial fibonacci",d:"Funcao chama a si mesma. Caso base + caso recursivo. factorial, fibonacci, torre de Hanoi. Limite ~1000."}]},
{name:"Arquivos, Erros e Modulos",books:["Automate the Boring Stuff \u2014 Al Sweigart (gratuito)","Python Cookbook \u2014 Beazley & Jones","Fluent Python \u2014 Luciano Ramalho"],items:[
{w:"Ler/escrever: with open(), JSON, CSV, pathlib",s:"python file handling json csv, ler escrever arquivos python, python pathlib",d:"with open('arq','r') as f: f.read(). json.load/dump. csv.DictReader. Path().exists()."},
{w:"try/except/else/finally, excecoes customizadas",s:"python error handling try except, tratamento excecoes python, python custom exception",d:"try: arriscado / except ValueError: tratar / else: se ok / finally: sempre. raise CustomError()."},
{w:"Modulos, imports, pip, venv (ambientes virtuais)",s:"python modules imports pip venv, ambiente virtual python, python virtual environment",d:"import math. pip install pacote. python3 -m venv .venv. requirements.txt. NUNCA instale globalmente."},
{w:"Biblioteca padrao: os, sys, math, random, datetime, collections, itertools",s:"python standard library useful modules, biblioteca padrao python, python os sys random datetime",d:"os: sistema. math: sqrt,pi. random: randint,choice. datetime: now,strftime. collections: Counter,defaultdict,deque."}]},
{name:"Projetos Praticos",books:["Automate the Boring Stuff \u2014 Al Sweigart","Python Projects for Beginners \u2014 Connor Milliken","Impractical Python Projects \u2014 Lee Vaughan"],items:[
{w:"Projeto 1: Calculadora com menu e historico",s:"python calculator project, projeto calculadora python, python beginner project",d:"Menu interativo, funcoes por operacao, historico, salvar em arquivo. Exercita: input, condicionais, funcoes, loops, arquivos."},
{w:"Projeto 2: Jogo (adivinhacao / forca / quiz)",s:"python game project, jogo forca python, python text game",d:"random + dicas + pontuacao. Exercita: random, loops, strings, listas."},
{w:"Projeto 3: Gerenciador CRUD com JSON",s:"python CRUD json project, gerenciador tarefas python, python todo list",d:"Adicionar, listar, buscar, editar, remover + JSON. Seu primeiro CRUD!"},
{w:"Projeto 4: Consumir API publica com requests",s:"python requests API project, python consume API, python API tutorial",d:"pip install requests. PokeAPI, GitHub API, OpenWeather. Processar JSON. Exercita: pip, requests, dicts."},
{w:"Projeto 5: Automatizar tarefa chata",s:"python automation project, automatizar tarefas python, python script automate",d:"Renomear arquivos, organizar downloads, web scraping (BeautifulSoup), enviar emails. AUTOMACAO = superpoder."}]}]},
{name:"\u{1F4D0} Matematica Fundamental",topics:[
{name:"Pre-Calculo e Revisao",books:["Pre-Calculo \u2014 Demana, Waits & Foley","Matematica Basica \u2014 Iezzi & Murakami","Khan Academy Pre-Algebra + Algebra (gratuito)"],items:[
{w:"Aritmetica: fracoes, porcentagem, proporcao, notacao cientifica",s:"arithmetic fractions percentages, aritmetica fracoes porcentagem, math review basics",d:"1/2 + 1/3 = 5/6. 25% de 200 = 50. Proporcao direta/inversa. Notacao cientifica: 3.2 x 10^6. Esses sao blocos basicos pra TUDO que vem depois."},
{w:"Algebra basica: equacoes, inequacoes, fatoracao, polinomios",s:"algebra basics equations, algebra basica equacoes, solving linear quadratic equations",d:"2x + 3 = 7 -> x=2. Fatorar: x2-4=(x+2)(x-2). Bhaskara: x=(-b+-sqrt(b2-4ac))/2a. Se nao dominar isso, calculo vai ser impossivel."},
{w:"Funcoes: conceito, dominio, imagem, grafico, tipos (linear, quadratica, exponencial, log)",s:"functions math domain range graph, funcoes matematica tipos graficos, linear quadratic exponential",d:"f(x) = regra que transforma entrada em saida. Linear: reta. Quadratica: parabola. Exponencial: crescimento rapido. Log: inversa da exponencial. ENTENDA graficos!"},
{w:"Trigonometria basica: sen, cos, tan, circulo unitario",s:"trigonometry basics sin cos tan, trigonometria basica, unit circle tutorial",d:"SOH-CAH-TOA. Circulo unitario: sen=y, cos=x. Radianos: pi=180. Identidades: sen2+cos2=1. Aparece em sinais, rotacoes, ondas."},
{w:"Geometria analitica: plano cartesiano, distancia, reta, circunferencia",s:"analytic geometry basics, geometria analitica plano cartesiano, coordinate geometry",d:"Ponto (x,y). Distancia entre pontos. Equacao da reta: y=mx+b. Coeficiente angular = inclinacao. Circunferencia: (x-a)2+(y-b)2=r2."},
{w:"Sequencias, series e somatorios (notacao sigma)",s:"sequences series summation notation, sequencias series somatorio, sigma notation math",d:"Aritmetica: a, a+d, a+2d. Geometrica: a, ar, ar2. Somatorio: Sigma de i=1 ate n de f(i). PA e PG. Fatorial: 5!=120. Precisa pra analise de algoritmos e probabilidade."}]},
{name:"Matematica Discreta",books:["Discrete Mathematics \u2014 Kenneth Rosen","Mathematics for Computer Science \u2014 MIT (gratuito)","Matematica Discreta \u2014 Rosen (traducao BR)"],items:[
{w:"Logica Proposicional: AND OR NOT, tabelas verdade, De Morgan",s:"propositional logic truth tables, logica proposicional tabela verdade, discrete math logic",d:"Conectivos: AND OR NOT -> <->. Tabelas verdade. De Morgan: NOT(A AND B) = (NOT A) OR (NOT B). Diretamente aplicavel a if/and/or em codigo."},
{w:"Logica de Predicados: quantificadores universal e existencial",s:"predicate logic quantifiers, logica predicados quantificadores, forall exists logic",d:"Para todo (universal): todo aluno tem nota. Existe (existencial): existe aluno com nota 10. Base de queries SQL e provas formais."},
{w:"Teoria dos Conjuntos: operacoes, diagramas de Venn, complemento",s:"set theory operations Venn, teoria conjuntos operacoes, sets math basics",d:"Uniao, intersecao, diferenca, complemento. Diagramas de Venn. Pertinencia (esta em), subconjunto (contido em). Base dos tipos de dados Set."},
{w:"Funcoes e Relacoes: injetora, sobrejetora, bijetora, equivalencia",s:"functions relations discrete math, funcoes injetora sobrejetora bijetora, equivalence relations",d:"Funcao: cada entrada tem 1 saida. Injetora: entradas diferentes, saidas diferentes. Sobrejetora: cobre toda imagem. Bijetora: ambas. Relacao de equivalencia: reflexiva+simetrica+transitiva."},
{w:"Inducao matematica: base + passo indutivo",s:"mathematical induction tutorial, inducao matematica, proof by induction examples",d:"Provar pra n=1 (base). Assumir verdade pra k, provar pra k+1 (passo). Prova que algo vale pra TODOS os naturais. Fundamental pra provar correcao de algoritmos."},
{w:"Contagem: permutacao, combinacao, principio multiplicativo, pigeonhole",s:"permutations combinations counting, permutacao combinacao, combinatorics basics",d:"P(n,k)=n!/(n-k)!. C(n,k)=n!/(k!(n-k)!). Multiplicativo: 3 camisas x 2 calcas = 6 looks. Pigeonhole: se 13 pessoas, pelo menos 2 nascem no mesmo mes."},
{w:"Teoria dos Grafos intro: vertices, arestas, grau, caminhos, ciclos, arvores",s:"graph theory basics, teoria grafos vertices arestas, graphs paths cycles trees",d:"Grafo = vertices + arestas. Grau: quantas arestas. Caminho: sequencia de vertices. Ciclo: caminho fechado. Arvore: grafo conexo sem ciclo. Base de redes sociais, mapas, algoritmos."},
{w:"Relacoes de recorrencia: Fibonacci, Torre de Hanoi",s:"recurrence relations Fibonacci, relacoes recorrencia, recurrence relation examples",d:"T(n) = T(n-1) + T(n-2) (Fibonacci). T(n) = 2T(n-1)+1 (Hanoi). Resolve com arvore de recursao ou teorema mestre. Liga matematica com programacao."}]},
{name:"Calculo I",books:["Calculo Vol.1 \u2014 James Stewart","Calculus Made Easy \u2014 Thompson (gratuito)","Calculo Vol.1 \u2014 Guidorizzi"],items:[
{w:"Limites: intuicao, propriedades, limites laterais, infinitos",s:"limits calculus intuition, limites calculo 1, limits properties lateral",d:"Limite = valor que f(x) se aproxima quando x tende a c. Propriedades: soma, produto, quociente. Laterais: pela esquerda e direita. Limites infinitos: assintotas."},
{w:"Limites: tecnicas de resolucao (substituicao, fatoracao, L'Hopital)",s:"limit solving techniques, resolver limites calculo, L'Hopital rule indeterminate",d:"Substituicao direta (se nao der 0/0). Fatoracao. Racionalizacao. L'Hopital: derivar em cima e embaixo quando 0/0 ou inf/inf. Limites notaveis: sen(x)/x->1."},
{w:"Continuidade: definicao, tipos de descontinuidade",s:"continuity calculus, continuidade funcoes calculo, types of discontinuity",d:"Continua em c: f(c) existe, lim existe, lim = f(c). Descontinuidade: removivel (furo), salto, infinita. TVI: se continua e f(a)<0<f(b), existe raiz entre a e b."},
{w:"Derivadas: definicao, interpretacao geometrica (reta tangente), taxa de variacao",s:"derivatives definition tangent line, derivadas definicao reta tangente, rate of change calculus",d:"Derivada = limite da razao incremental = inclinacao da reta tangente = taxa de variacao instantanea. f'(x) = lim (f(x+h)-f(x))/h. Velocidade = derivada da posicao."},
{w:"Regras de derivacao: potencia, produto, quociente, cadeia",s:"derivative rules power product quotient chain, regras derivacao, chain rule calculus",d:"Potencia: (x^n)'=nx^(n-1). Produto: (fg)'=f'g+fg'. Quociente: (f/g)'=(f'g-fg')/g2. Cadeia: (f(g(x)))'=f'(g(x))*g'(x). CADEIA e a mais importante!"},
{w:"Derivadas de trig, exponencial, log",s:"derivative trigonometric exponential logarithm, derivadas trig exp log",d:"(sen x)'=cos x. (cos x)'=-sen x. (e^x)'=e^x. (ln x)'=1/x. (a^x)'=a^x ln a. Combinando com regra da cadeia resolve quase tudo."},
{w:"Aplicacoes: max/min, otimizacao, taxas relacionadas",s:"calculus optimization max min, aplicacoes derivadas otimizacao, related rates",d:"f'=0 nos pontos criticos. f''>0 minimo, f''<0 maximo. Otimizacao: maximizar area/minimizar custo. Gradiente descendente em ML e derivada pura!"},
{w:"Integrais: anti-derivada, integral definida, TFC",s:"integrals antiderivative definite, integral definida TFC, fundamental theorem calculus",d:"Integral indefinida = anti-derivada + C. Integral definida = area sob a curva. TFC: integral de a ate b de f(x)dx = F(b)-F(a). Liga derivada com integral."},
{w:"Tecnicas de integracao: substituicao, partes, fracoes parciais",s:"integration techniques substitution parts, tecnicas integracao, integration by parts substitution",d:"Substituicao: u=g(x). Partes: integral(u dv)=uv-integral(v du). Fracoes parciais: decompor racional. Integrais trig. Aplicacao em probabilidade: P(a<X<b) = integral de f(x)."}]},
{name:"Algebra Linear (Inicio)",books:["Algebra Linear \u2014 David C. Lay","Intro to Linear Algebra \u2014 Gilbert Strang","Coding the Matrix \u2014 Philip Klein"],items:[
{w:"Vetores: operacoes, produto escalar, norma, projecao",s:"vectors linear algebra operations, vetores algebra linear, vector dot product norm projection",d:"Vetor = lista de numeros = direcao+magnitude. Soma, escalar, dot product (similaridade), norma (comprimento), projecao. Em ML cada dado e um vetor."},
{w:"Matrizes: operacoes, multiplicacao, transposta",s:"matrix operations multiplication, matrizes operacoes multiplicacao, matrix tutorial",d:"Soma, escalar, multiplicacao (AB != BA!), transposta. Matriz = transformacao linear. Rotacao, escala, cisalhamento."},
{w:"Determinante e Inversa: quando existe, como calcular",s:"matrix determinant inverse, determinante inversa matriz, invertible matrix",d:"det(A)!=0 -> inversivel. Inversa: AA^{-1}=I. 2x2: formula direta. 3x3: cofatores. np.linalg.inv(A)."},
{w:"Sistemas lineares: eliminacao de Gauss, escalonamento",s:"gaussian elimination linear systems, sistemas lineares Gauss, row echelon form",d:"Ax=b. Escalonar matriz aumentada [A|b]. Forma escada. Solucao unica, infinitas, ou nenhuma. np.linalg.solve(A,b)."},
{w:"Espacos vetoriais: base, dimensao, subespacos, independencia linear",s:"vector spaces basis dimension, espacos vetoriais base dimensao, linear independence",d:"Base: vetores minimos que geram o espaco. Dimensao: tamanho da base. LI: nenhum e combinacao dos outros. R^n: espaco n-dimensional."}]}]},
{name:"\u{1F310} Web, Git & Ferramentas",topics:[
{name:"HTML",books:["HTML & CSS \u2014 Jon Duckett","Learning Web Design \u2014 Jennifer Robbins","MDN Web Docs (gratuito)"],items:[
{w:"Estrutura: DOCTYPE, html, head, body, meta tags",s:"HTML document structure, html head body meta, HTML basics tutorial",d:"<!DOCTYPE html> declara HTML5. <html> <head>(meta, title, links) <body>(conteudo visivel). Meta: charset, viewport."},
{w:"Tags semanticas: header, nav, main, section, article, footer, aside",s:"HTML semantic tags, html5 semantico, semantic HTML best practices",d:"Semantica = significado. <header> nao e <div class=header>. Acessibilidade, SEO, legibilidade. Screen readers usam semantica."},
{w:"Formularios: input, select, textarea, radio, checkbox, button, labels",s:"HTML forms tutorial, html formularios input types, HTML form validation",d:"<form action method>. Tipos: text, email, password, number, date, file. required, placeholder, pattern. Label + for = acessibilidade."},
{w:"Tabelas, listas, links, imagens, multimedia",s:"HTML tables lists links images, html tags completo, HTML media elements",d:"<table> <tr> <td>. <ul> <ol> <li>. <a href>. <img src alt>. <video> <audio>. <iframe>. Sempre alt em imagens."},
{w:"Acessibilidade: ARIA, alt text, contraste, teclado",s:"web accessibility ARIA, acessibilidade web, HTML accessibility best practices",d:"ARIA roles/labels pra screen readers. Alt descritivo em imagens. Contraste minimo 4.5:1. Tudo navegavel por teclado (Tab)."}]},
{name:"CSS",books:["CSS in Depth \u2014 Keith Grant","HTML & CSS \u2014 Jon Duckett","CSS Tricks (gratuito)"],items:[
{w:"Seletores, cascata, especificidade, heranca",s:"CSS selectors specificity cascade, seletores CSS especificidade, CSS inheritance",d:"Seletores: tag, .classe, #id, [attr], :pseudo. Especificidade: inline > id > classe > tag. !important (evite). Heranca: color sim, padding nao."},
{w:"Box Model: content, padding, border, margin",s:"CSS box model tutorial, box model CSS, CSS margin padding border",d:"Tudo e caixa. content > padding > border > margin. box-sizing: border-box (inclui padding no width). Margens colapsam verticalmente."},
{w:"Flexbox: eixos, alinhamento, distribuicao",s:"CSS flexbox tutorial complete, flexbox layout, flexbox froggy game",d:"display:flex. flex-direction: row/column. justify-content (eixo principal). align-items (eixo cruzado). flex-grow, flex-shrink, flex-basis. Jogue Flexbox Froggy!"},
{w:"Grid: linhas, colunas, areas, template",s:"CSS grid tutorial complete, grid layout CSS, CSS grid garden game",d:"display:grid. grid-template-columns/rows. fr unit. grid-area. gap. repeat(). minmax(). Jogue CSS Grid Garden!"},
{w:"Responsividade: media queries, mobile-first, unidades relativas",s:"CSS responsive design media queries, mobile first CSS, responsive units rem em vw vh",d:"@media (max-width: 768px). Mobile-first: comece pequeno, adicione complexidade. rem/em: relativo a font-size. vw/vh: viewport. clamp() pra fluid."},
{w:"Variaveis CSS, transicoes, animacoes, pseudo-elementos",s:"CSS custom properties variables, CSS transitions animations, pseudo elements before after",d:"--cor: #333; var(--cor). transition: all 0.3s. @keyframes. ::before ::after. transform: scale, rotate, translate. Perfomance: use transform e opacity."}]},
{name:"JavaScript Basico",books:["Eloquent JavaScript \u2014 Haverbeke (gratuito)","JavaScript: The Good Parts \u2014 Crockford","You Don't Know JS \u2014 Kyle Simpson (gratuito)"],items:[
{w:"Tipos, variaveis (let/const/var), operadores",s:"javascript types variables let const, javascript basics tutorial, JS data types",d:"let: reatribuivel. const: fixo. var: evite (escopo confuso). Tipos: string, number, boolean, null, undefined, object, symbol. typeof."},
{w:"Funcoes: declaration, expression, arrow, closures",s:"javascript functions arrow closure, funcoes javascript, JS function types",d:"function nome(){} vs const nome = () => {}. Closures: funcao interna acessa escopo externo. Callback: funcao como argumento."},
{w:"Arrays e objetos: metodos, destructuring, spread",s:"javascript arrays objects methods, JS destructuring spread, array map filter reduce",d:".map .filter .reduce .find .some .every .forEach. Destructuring: const {nome} = obj. Spread: {...obj, novo: 1}. Objetos: chave-valor."},
{w:"DOM: querySelector, createElement, classList, eventos",s:"javascript DOM manipulation, DOM events addEventListener, javascript DOM tutorial",d:"document.querySelector('.classe'). .textContent .innerHTML .classList.add/remove/toggle. addEventListener('click', fn). Event delegation."},
{w:"Fetch API, Promises, async/await, JSON",s:"javascript fetch API async await, promises javascript, JS API call tutorial",d:"fetch(url).then(r=>r.json()).then(data=>...). async/await: mais legivel. try/catch pra erros. JSON.parse/stringify."},
{w:"ES6+: template literals, modules (import/export), optional chaining, nullish coalescing",s:"javascript ES6 features, ES6 modules import export, JS modern features",d:"Template: `Oi ${nome}`. Modules: export/import. ?. (optional chaining): obj?.prop. ?? (nullish): valor ?? default. Classes, symbols, iterators."}]},
{name:"Git & GitHub",books:["Pro Git \u2014 Scott Chacon (gratuito)","Learning Git \u2014 Anna Skoulikari","Git Pocket Guide \u2014 Silverman"],items:[
{w:"Conceitos: repositorio, staging area, commit, branch, remote",s:"git concepts repository staging commit, conceitos git basico, git workflow explained",d:"Working dir > staging (git add) > commit (snapshot). Branch: linha paralela. Remote: copia no servidor (GitHub). Clone: copiar. Push: enviar. Pull: receber."},
{w:"Comandos: init, add, commit, status, log, diff, checkout, reset",s:"git commands tutorial, comandos git essenciais, git init add commit log",d:"git init. git add . / git add arquivo. git commit -m 'feat: msg'. git status. git log --oneline. git diff. git checkout -- arquivo (desfazer)."},
{w:"Branches: criar, trocar, merge, resolver conflitos",s:"git branch merge conflicts, git branches tutorial, resolve merge conflicts",d:"git branch nome. git checkout -b nome. git merge. Conflitos: <<<< ==== >>>> editar manualmente. git rebase: reescrever historico (limpo mas cuidado)."},
{w:"GitHub: repos, fork, clone, PRs, issues, code review",s:"github tutorial complete, github pull request, github fork clone workflow",d:"Fork: copiar repo de outro. Clone: baixar local. PR: propor mudancas. Code review: revisar antes de merge. Issues: rastrear bugs/features."},
{w:"Commits semanticos: conventional commits (feat, fix, docs, refactor)",s:"conventional commits, commits semanticos, git commit message best practices",d:"feat: nova funcionalidade. fix: correcao. docs: documentacao. refactor: reestruturar. chore: manutenção. BREAKING CHANGE: incompativel. Historico limpo e pesquisavel."},
{w:"GitHub Actions e GitHub Pages: CI/CD e hospedagem",s:"github actions CI CD tutorial, github pages deploy, github actions workflow",d:"Actions: YAML workflow. On push/PR. Steps: lint, test, build, deploy. Pages: hospedar site estatico gratis. Settings > Pages > branch main."},
{w:".gitignore, tags, stash, cherry-pick, bisect",s:"gitignore template, git stash cherry-pick bisect, git advanced commands",d:".gitignore: node_modules/, .env, __pycache__/. git stash: guardar mudancas temporariamente. git tag v1.0. cherry-pick: pegar commit especifico. bisect: achar bug."}]},
{name:"Ferramentas do Dev",books:["The Missing Semester \u2014 MIT (gratuito)","Practical Vim \u2014 Drew Neil","Unix & Linux SysAdmin \u2014 Nemeth"],items:[
{w:"VS Code: atalhos, extensoes, debugging, settings sync",s:"VS Code productivity tips extensions, VS Code debugging, VS Code shortcuts",d:"Ctrl+P (arquivo), Ctrl+Shift+P (comando), Ctrl+D (selecionar), Alt+up/down (mover linha). Extensions: Python, Prettier, GitLens, Error Lens, Thunder Client. F5 debug."},
{w:"Markdown: sintaxe, READMEs, documentacao",s:"markdown tutorial complete, markdown syntax, writing good README github",d:"# Titulo. **negrito**. *italico*. [link](url). ```codigo```. - lista. README: descricao, install, uso, licenca. Documentar e profissional."},
{w:"Terminal multiplexers: tmux (multiplas sessoes)",s:"tmux tutorial beginners, tmux terminal multiplexer, tmux cheatsheet",d:"tmux: rodar multiplos terminais em 1 janela. Sessoes persistem se desconectar (SSH). Ctrl+B c(nova janela), Ctrl+B %(split). Muito util em servidores."},
{w:"Ferramentas de linha: curl, wget, jq, awk, sed, xargs",s:"curl wget jq command line, linux command line tools, awk sed tutorial",d:"curl: HTTP requests. wget: download. jq: processar JSON. awk: processar texto. sed: substituir texto. xargs: pipeline. Combinadas sao poderosas."}]}]},
{name:"\u{1F5C4}\u{FE0F} Banco de Dados Introducao",topics:[
{name:"Conceitos Fundamentais",books:["Database System Concepts \u2014 Silberschatz","Learning SQL \u2014 Alan Beaulieu","SQL em 10 Minutos \u2014 Ben Forta"],items:[
{w:"O que e banco de dados? Relacional vs nao-relacional",s:"what is database relational vs NoSQL, banco de dados relacional, database types comparison",d:"BD organiza dados pra consulta eficiente. Relacional: tabelas com relacoes (SQL). NoSQL: documentos, chave-valor, grafos. 90% dos casos: comece com relacional."},
{w:"Tabelas, colunas, linhas, tipos de dados (INT, VARCHAR, DATE, BOOLEAN...)",s:"SQL data types, tipos dados SQL, database table columns rows",d:"Tabela = entidade. Coluna = atributo. Linha = registro. INT: numeros. VARCHAR(255): texto. DATE: data. BOOLEAN: true/false. DECIMAL: dinheiro."},
{w:"Chaves primarias (PK), estrangeiras (FK), unicidade",s:"primary key foreign key, chave primaria estrangeira, SQL constraints unique",d:"PK: identifica unico (nunca nulo). FK: referencia outra tabela. UNIQUE: sem duplicatas. NOT NULL. DEFAULT. CHECK."},
{w:"Relacionamentos: 1:1, 1:N, N:N (tabela ponte)",s:"database relationships one to many, relacionamentos banco dados, many to many junction table",d:"1:1: pessoa-CPF. 1:N: autor-livros. N:N: alunos-materias (precisa tabela ponte). Diagramas ER: retangulo=entidade, losango=relacao."},
{w:"Normalizacao: 1NF, 2NF, 3NF, quando desnormalizar",s:"database normalization 1NF 2NF 3NF, normalizacao banco dados, when to denormalize",d:"1NF: atomico (sem listas). 2NF: sem dependencia parcial. 3NF: sem dependencia transitiva. Normalizar = menos duplicacao. Desnormalizar = mais velocidade (trade-off)."}]},
{name:"SQL na Pratica",books:["Learning SQL \u2014 Alan Beaulieu","SQL em 10 Minutos \u2014 Ben Forta","The Art of SQL \u2014 Faroult"],items:[
{w:"CREATE TABLE, ALTER, DROP, constraints",s:"SQL CREATE TABLE tutorial, SQL DDL commands, SQL constraints tutorial",d:"CREATE TABLE usuarios (id SERIAL PK, nome VARCHAR(100) NOT NULL, email VARCHAR(255) UNIQUE). ALTER TABLE ADD/DROP COLUMN. DROP TABLE (cuidado!)."},
{w:"INSERT, SELECT, UPDATE, DELETE com WHERE",s:"SQL CRUD tutorial, SQL SELECT INSERT UPDATE DELETE, SQL WHERE clause",d:"INSERT INTO t (col) VALUES (val). SELECT col FROM t WHERE cond ORDER BY col LIMIT n. UPDATE t SET col=val WHERE cond. NUNCA esqueca WHERE no UPDATE/DELETE!"},
{w:"Filtros: WHERE, AND/OR, IN, BETWEEN, LIKE, IS NULL",s:"SQL WHERE filters, SQL LIKE IN BETWEEN, SQL filter conditions",d:"WHERE idade > 18 AND cidade='SP'. IN ('SP','RJ'). BETWEEN 10 AND 20. LIKE 'Jo%' (comeca com Jo). IS NULL / IS NOT NULL."},
{w:"ORDER BY, LIMIT, OFFSET, DISTINCT, aliases",s:"SQL ORDER BY LIMIT DISTINCT, SQL aliases AS, SQL sorting pagination",d:"ORDER BY col ASC/DESC. LIMIT 10 OFFSET 20 (paginacao). DISTINCT: sem duplicatas. AS: alias pra colunas e tabelas."},
{w:"JOINs: INNER, LEFT, RIGHT, FULL, CROSS, self-join",s:"SQL JOINs tutorial visual, SQL JOIN types explained, SQL INNER LEFT RIGHT JOIN",d:"INNER: ambas tem match. LEFT: todos da esquerda + match. RIGHT: inverso. FULL: todos. CROSS: produto cartesiano. Self-join: tabela consigo mesma."},
{w:"Agregacoes: COUNT, SUM, AVG, MIN, MAX, GROUP BY, HAVING",s:"SQL aggregate functions GROUP BY HAVING, SQL COUNT SUM AVG, SQL grouping",d:"SELECT cidade, COUNT(*) FROM t GROUP BY cidade HAVING COUNT(*)>5. Agregacao = resumir dados. HAVING filtra DEPOIS de agrupar (WHERE filtra antes)."},
{w:"Subqueries e CTEs (Common Table Expressions)",s:"SQL subquery CTE tutorial, SQL WITH clause, SQL nested queries",d:"Subquery: SELECT * FROM t WHERE id IN (SELECT id FROM ...). CTE: WITH nome AS (SELECT ...) SELECT * FROM nome. CTEs sao mais legiveis."},
{w:"SQLite pra praticar + ferramentas visuais",s:"SQLite tutorial python, DB Browser SQLite, online SQL practice",d:"Banco em arquivo. DB Browser: GUI gratis. Python: import sqlite3. Online: sqliteonline.com, w3schools SQL. Projetos: contatos, catalogo, gastos."}]}]},
{name:"\u{1F50C} Eletronica & Hardware",topics:[
{name:"Eletricidade Basica",books:["Practical Electronics for Inventors \u2014 Scherz & Monk","Make: Electronics \u2014 Charles Platt","Elementos de Eletronica Digital \u2014 Idoeta & Capuano"],items:[
{w:"Tensao (V), corrente (A), resistencia (Ohm), potencia (W)",s:"voltage current resistance power, tensao corrente resistencia, basic electricity concepts",d:"Tensao (V): pressao eletrica. Corrente (A): fluxo de eletrons. Resistencia (Ohm): oposicao. Potencia (W) = V*I. Analogia: agua no cano."},
{w:"Lei de Ohm: V = R * I, circuitos serie e paralelo",s:"ohm's law circuits series parallel, lei de Ohm circuitos, series parallel resistance",d:"V=RI. Serie: mesma corrente, tensoes somam, R_total = R1+R2. Paralelo: mesma tensao, correntes somam, 1/R_total = 1/R1+1/R2."},
{w:"Componentes: resistor, capacitor, indutor, diodo, LED, transistor",s:"electronic components basics, componentes eletronicos basicos, resistor capacitor diode transistor",d:"Resistor: limita corrente (codigo cores). Capacitor: armazena carga. Diodo: corrente 1 direcao. LED: luz. Transistor: chave/amplificador (base da computacao!)."},
{w:"Protoboard, multimetro, fonte, soldagem basica",s:"breadboard tutorial, multimeter basics, soldering beginners",d:"Protoboard: prototipar sem solda. Multimetro: medir V, I, R, continuidade. Fonte: fornecer tensao estavel. Soldagem: habilidade essencial pra projetos."}]},
{name:"Eletronica Digital",books:["Digital Design \u2014 Morris Mano","Elementos de Eletronica Digital \u2014 Idoeta & Capuano","Digital Fundamentals \u2014 Floyd"],items:[
{w:"Portas logicas: AND, OR, NOT, NAND, NOR, XOR, XNOR",s:"logic gates AND OR NOT NAND, portas logicas eletronica digital, logic gates truth table",d:"Fisicamente: transistores combinados. AND: ambos 1. OR: pelo menos 1. NOT: inverte. NAND: NOT AND (universal). XOR: diferente. Tabelas verdade."},
{w:"Algebra booleana, simplificacao, mapas de Karnaugh",s:"boolean algebra simplification, Karnaugh map, algebra booleana simplificacao",d:"A+A'=1. A*A'=0. De Morgan. Karnaugh: simplificacao visual (2-4 variaveis). Minimizar logica = menos portas = mais barato/rapido."},
{w:"Circuitos combinacionais: somador, MUX, decodificador, comparador",s:"combinational circuits adder MUX, circuitos combinacionais somador, multiplexer decoder",d:"Somador: half-adder (2 bits) e full-adder (3 bits, com carry). MUX: seleciona 1 de N entradas. Decodificador: N bits > 2^N saidas."},
{w:"Flip-flops (SR, D, JK, T), registradores, contadores",s:"flip flops SR D JK, registradores contadores, sequential circuits tutorial",d:"Flip-flop: armazena 1 bit (memoria!). D: mais usado (dado + clock). Registrador: grupo de flip-flops. Contador: sequencia automatica."},
{w:"Maquina de estados finitos (FSM): Mealy e Moore",s:"finite state machine FSM, maquina de estados, Mealy Moore state machine",d:"FSM: estados + transicoes + entradas + saidas. Mealy: saida depende de estado+entrada. Moore: saida so depende do estado. Usada em protocolos, controle, parsers."}]}]}
]},
{id:"intermediate",name:"\u{1F7E1} INTERMEDIARIO",css:"yellow",time:"~12-24 meses",desc:"Profundidade. Voce ja programa \u2014 agora entenda COMO e POR QUE.",areas:[
{name:"\u{1F4CA} Estruturas de Dados & Algoritmos",topics:[
{name:"Estruturas de Dados",books:["Entendendo Algoritmos \u2014 Aditya Bhargava","Introduction to Algorithms (CLRS) \u2014 Cormen et al.","Data Structures in Python \u2014 Goodrich et al."],items:[
{w:"Listas Ligadas: simples, dupla, circular",s:"linked list python, lista ligada implementacao, singly doubly linked list",d:"Cada no aponta pro proximo. Insercao O(1), busca O(n). Implemente do zero: Node(data, next)."},
{w:"Pilhas (LIFO) e Filas (FIFO)",s:"stack queue python, pilha fila estrutura dados, stack queue tutorial",d:"Pilha: push/pop (ctrl+Z, parenteses). Fila: enqueue/dequeue (BFS). Deque: duas pontas."},
{w:"Tabelas Hash: funcao hash, colisoes, Dict",s:"hash table python, tabela hash colisoes, hash map implementation",d:"Chave>indice via hash. Colisao: chaining ou open addressing. Dict do Python = hash table. O(1) medio."},
{w:"Arvores: binaria, BST, AVL, Heap",s:"binary search tree AVL heap python, arvore BST, heap priority queue",d:"BST: esquerda<raiz<direita. AVL: auto-balanceia. Heap: min/max no topo = fila prioridade."},
{w:"Grafos: lista/matriz adjacencia",s:"graph data structure python, grafos lista adjacencia, graph representation",d:"Dict: {A:[(B,5),(C,3)]}. Dirigido vs nao. Ponderado (custos nas arestas)."},
{w:"Trie, Segment Tree, Union-Find",s:"trie segment tree union find, advanced data structures python",d:"Trie: autocompletar. Segment: range queries. Union-Find: componentes conectados."}]},
{name:"Algoritmos",books:["Entendendo Algoritmos \u2014 Aditya Bhargava","Algorithm Design Manual \u2014 Skiena","Competitive Programming \u2014 Halim"],items:[
{w:"Big O: analise de complexidade",s:"big O notation tutorial, complexidade algoritmos, time space complexity",d:"O(1)<O(log n)<O(n)<O(n log n)<O(n2)<O(2^n). Analise cada loop."},
{w:"Busca linear e binaria",s:"binary search python, busca binaria, binary search variations",d:"Linear O(n). Binaria O(log n) em dados ordenados. 1 bilhao = ~30 passos."},
{w:"Ordenacao: bubble, merge, quick, heap, counting, radix",s:"sorting algorithms comparison python, algoritmos ordenacao, merge quick sort",d:"O(n2): bubble, selection. O(n log n): merge, quick, heap. O(n+k): counting, radix."},
{w:"Recursao, Divide & Conquer, Backtracking",s:"divide conquer backtracking, backtracking N queens sudoku python",d:"D&C: dividir>resolver>combinar. Backtracking: explorar+podar (N-Queens, Sudoku)."},
{w:"Programacao Dinamica: memoization e tabulacao",s:"dynamic programming python, programacao dinamica, DP classic problems",d:"Top-down (cache) e bottom-up (tabela). Fibonacci, knapsack, coin change, LCS."},
{w:"Algoritmos Gulosos (Greedy)",s:"greedy algorithm examples python, algoritmo guloso, greedy vs DP",d:"Escolha otima local. Scheduling, Huffman, Kruskal, Dijkstra."},
{w:"Grafos: BFS, DFS, Dijkstra, Kruskal, Topological Sort",s:"graph algorithms BFS DFS Dijkstra python, shortest path MST",d:"BFS: fila. DFS: pilha/recursao. Dijkstra: pesos positivos. MST: Kruskal/Prim."},
{w:"Pratica: LeetCode, HackerRank, Beecrowd",s:"leetcode beginner guide, competitive programming, beecrowd exercicios",d:"1 problema/dia. Por categoria. Beecrowd (BR). Entenda o padrao, nao decore."}]}]},
{name:"\u{1F40D} Python Intermediario & OOP",topics:[
{name:"OOP em Python",books:["Python Fluente \u2014 Luciano Ramalho","Head First OOP \u2014 McLaughlin et al.","OO Thought Process \u2014 Weisfeld"],items:[
{w:"Classes, objetos, __init__, self",s:"python classes OOP tutorial, programacao orientada objetos python, python __init__",d:"class Pessoa: def __init__(self,nome): self.nome=nome. Objeto: p=Pessoa('Kaio')."},
{w:"Encapsulamento, heranca, polimorfismo, ABC",s:"python OOP inheritance polymorphism, pilares OOP python, python ABC abstract",d:"_protected, __private. class Dog(Animal). Polimorfismo: mesmo metodo, diferente comportamento. ABC: classes abstratas."},
{w:"Dunder methods e dataclasses",s:"python magic methods dunder, python dataclass tutorial, python __str__ __eq__",d:"__str__ __repr__ __eq__ __lt__ __len__ __getitem__. @dataclass gera init, repr, eq automatico."},
{w:"Composicao vs heranca, SOLID em Python",s:"composition vs inheritance python, SOLID python, python design principles",d:"Composicao (tem-um) > heranca (e-um). SOLID: responsabilidade unica, aberto/fechado, Liskov, segregacao, inversao."}]},
{name:"Python Avancado",books:["Effective Python \u2014 Brett Slatkin","Python Fluente \u2014 Luciano Ramalho","Python Cookbook \u2014 Beazley & Jones"],items:[
{w:"Generators, iterators, itertools",s:"python generators itertools, generators yield python, python lazy evaluation",d:"yield: lazy (nao carrega tudo). itertools: chain, product, combinations, groupby."},
{w:"Context managers, type hints, mypy",s:"python context manager with, python type hints mypy, python typing",d:"with: __enter__/__exit__. def f(x: int) -> str. mypy pra checagem estatica."},
{w:"Testing: pytest, TDD, coverage",s:"python pytest TDD tutorial, python testing, pytest fixtures parametrize",d:"def test_soma(): assert soma(2,3)==5. Fixtures, parametrize. TDD: test>code>refactor."},
{w:"Concorrencia: threading, multiprocessing, asyncio",s:"python threading asyncio multiprocessing, python concurrency, python async await",d:"Threading: I/O-bound (GIL). Multiprocessing: CPU-bound. Asyncio: event loop, non-blocking."}]}]},
{name:"\u{1F310} Full-Stack",topics:[
{name:"Frontend: React + TypeScript",books:["Learning React \u2014 Banks & Porcello","Programming TypeScript \u2014 Boris Cherny","Road to React \u2014 Robin Wieruch"],items:[
{w:"React: componentes, props, state, hooks (useState, useEffect)",s:"react hooks tutorial 2025, react useState useEffect, react components props",d:"JSX. Props: pai>filho. State: dados locais. useEffect: side effects. useContext: estado global."},
{w:"TypeScript, Tailwind CSS, React Router",s:"typescript react tutorial, tailwind CSS, react router SPA",d:"TS: tipos estaticos, interfaces. Tailwind: utility-first CSS. Router: navegacao SPA."},
{w:"Testes: Jest + React Testing Library",s:"react testing library jest, frontend testing, component testing react",d:"render, screen, fireEvent, waitFor. Testar comportamento, nao implementacao."}]},
{name:"Backend: APIs REST",books:["Node.js Design Patterns \u2014 Casciaro","Flask Web Development \u2014 Grinberg","Designing Data-Intensive Apps \u2014 Kleppmann"],items:[
{w:"REST API: Express.js ou FastAPI, CRUD, status codes",s:"REST API tutorial express fastapi, API design, HTTP status codes",d:"GET POST PUT DELETE. 200 201 400 404 500. Middleware. Error handling. Rotas."},
{w:"Auth (JWT/OAuth), validacao, WebSockets, Swagger",s:"JWT authentication, OAuth 2.0, API validation Zod Pydantic, swagger openapi",d:"JWT: tokens stateless. OAuth: login social. Validacao: Zod/Pydantic. Swagger: docs. WebSocket: real-time."}]},
{name:"Banco de Dados Intermediario",books:["PostgreSQL Up and Running \u2014 Obe & Hsu","MongoDB Definitive Guide \u2014 Bradshaw","Redis in Action \u2014 Carlson"],items:[
{w:"PostgreSQL: indices, EXPLAIN, JSONB, views, ORM",s:"PostgreSQL indexes explain, ORM prisma SQLAlchemy, database optimization",d:"B-tree, GIN, GiST. EXPLAIN ANALYZE. ORM: Prisma(JS), SQLAlchemy(Py). Migrations: versionar schema."},
{w:"NoSQL (MongoDB, Redis), transacoes ACID",s:"MongoDB tutorial, Redis cache, ACID transactions database",d:"MongoDB: documentos flexiveis. Redis: cache sub-ms. ACID: atomicidade, consistencia, isolamento, durabilidade."}]}]},
{name:"\u{1F916} Introducao a IA & ML",topics:[
{name:"Data Science: NumPy, Pandas, Visualizacao",books:["Python for Data Analysis \u2014 Wes McKinney","Storytelling with Data \u2014 Knaflic","Estatistica Pratica p/ Cientistas de Dados \u2014 Bruce & Bruce"],items:[
{w:"NumPy: arrays, broadcasting, operacoes vetorizadas",s:"numpy tutorial, numpy arrays broadcasting, numpy linear algebra",d:"10-100x mais rapido que listas. Broadcasting, reshaping, random, linalg."},
{w:"Pandas: DataFrame, limpeza, merge, groupby, pivot",s:"pandas tutorial complete, pandas dataframe groupby, data cleaning pandas",d:"read_csv, fillna, dropna, groupby, merge, pivot_table, apply. Datetime."},
{w:"Matplotlib + Seaborn: graficos e visualizacao",s:"matplotlib seaborn tutorial, data visualization python, seaborn plots",d:"plot, bar, scatter, hist, heatmap, boxplot, pairplot. Sempre rotule eixos."},
{w:"EDA e Estatistica: distribuicoes, correlacoes, Bayes",s:"EDA tutorial python, exploratory data analysis, probability Bayes",d:"Media, mediana, desvio padrao, correlacao, outliers. P(A|B)=P(B|A)P(A)/P(B). Normal, Binomial, Poisson."}]},
{name:"ML Classico (Scikit-Learn)",books:["Hands-On Machine Learning \u2014 Aurelien Geron","ISLR \u2014 James et al. (gratuito)","Pattern Recognition & ML \u2014 Bishop"],items:[
{w:"Tipos: supervisionado, nao-sup, semi, RL",s:"types machine learning, tipos aprendizado maquina, supervised unsupervised",d:"Supervisionado: com rotulos. Nao-sup: sem. Semi: poucos. RL: recompensas."},
{w:"Regressao Linear e Logistica (do zero + sklearn)",s:"linear logistic regression scratch, regressao linear sklearn, gradient descent",d:"Linear: y=wx+b, MSE, gradiente. Logistica: sigmoid, classificacao. Implemente do zero primeiro!"},
{w:"Arvores, Random Forest, XGBoost/LightGBM",s:"decision tree random forest XGBoost, ensemble methods, gradient boosting",d:"Gini/entropia. Bagging (RF) vs Boosting (XGB). Muito usados em producao e Kaggle."},
{w:"KNN, SVM, Naive Bayes, Clustering (K-Means, DBSCAN)",s:"KNN SVM naive bayes clustering, K-means DBSCAN python, classification",d:"KNN: vizinhos. SVM: hiperplano. NB: probabilistico. K-Means: centroides. DBSCAN: densidade."},
{w:"Pipeline, Cross-Validation, GridSearch, Metricas",s:"sklearn pipeline cross validation GridSearch, ML metrics precision recall F1",d:"Pipeline encadeia. K-Fold CV. Grid/RandomSearch. Accuracy, Precision, Recall, F1, ROC-AUC."},
{w:"Feature Engineering, Scaling, Regularizacao L1/L2",s:"feature engineering scaling, regularization L1 L2, overfitting bias variance",d:"StandardScaler/MinMax. L1(Lasso) L2(Ridge) ElasticNet. Dropout, early stopping."}]}]},
{name:"\u{1F4D0} Matematica p/ ML",topics:[
{name:"Calculo Multivariavel",books:["Mathematics for Machine Learning \u2014 Deisenroth (gratuito)","Calculo Vol.2 \u2014 James Stewart","Vector Calculus \u2014 Marsden & Tromba"],items:[
{w:"Derivadas parciais e gradiente",s:"partial derivatives gradient, derivadas parciais gradiente, multivariable calculus",d:"Derivada parcial: derivar em relacao a uma variavel, fixando as outras. Gradiente: vetor de todas parciais = direcao de maior crescimento. Base do gradient descent!"},
{w:"Regra da cadeia multivariavel, Jacobiano",s:"chain rule multivariable jacobian, regra cadeia multivariavel, jacobian matrix",d:"Cadeia multi: dy/dt = (dy/dx1)(dx1/dt) + (dy/dx2)(dx2/dt). Jacobiano: matriz de todas derivadas parciais. Essencial pra backpropagation em redes neurais."},
{w:"Hessiana, pontos criticos, convexidade",s:"hessian matrix critical points, hessiana otimizacao, convex optimization basics",d:"Hessiana: matriz de segundas derivadas. Positiva definida = minimo local. Convexidade: funcao em forma de bacia (1 so minimo). Loss functions convexas sao mais faceis."},
{w:"Otimizacao: SGD, Momentum, Adam, learning rate",s:"SGD Adam optimizer, gradient descent variants, optimization deep learning",d:"SGD: atualizar pesos na direcao oposta ao gradiente. Momentum: acumula velocidade. Adam: adapta lr por parametro. Learning rate scheduling: warmup, cosine decay."}]},
{name:"Algebra Linear Avancada",books:["Linear Algebra Done Right \u2014 Axler","Mathematics for Machine Learning \u2014 Deisenroth (gratuito)","Matrix Computations \u2014 Golub & Van Loan"],items:[
{w:"Autovalores e autovetores: diagonalizacao",s:"eigenvalues eigenvectors diagonalization, autovalores autovetores, eigendecomposition",d:"Av = lambda*v. Autovetor: direcao que nao muda. Autovalor: quanto escala. PCA usa autovetores da covariancia. Diagonalizacao: A = PDP^-1."},
{w:"SVD: Singular Value Decomposition",s:"SVD singular value decomposition, SVD explained, SVD applications ML",d:"A = U*Sigma*V'. Decompoe qualquer matriz. Aplicacoes: PCA, compressao de imagem, sistemas de recomendacao, reducao de dimensionalidade."},
{w:"Normas L1, L2, Frobenius, produto interno em espacos de funcoes",s:"L1 L2 norm Frobenius, normas algebra linear, inner product spaces",d:"L1: soma dos absolutos (sparse). L2: raiz da soma dos quadrados (Euclidiana). Frobenius: norma de matriz. Regularizacao: L1 = Lasso, L2 = Ridge."},
{w:"Decomposicoes: LU, QR, Cholesky",s:"LU QR Cholesky decomposition, decomposicoes matrizes, matrix factorization",d:"LU: resolver sistemas. QR: minimos quadrados. Cholesky: matrizes simetricas positivas definidas (muito eficiente). Todas usadas em ML internamente."}]},
{name:"Probabilidade e Estatistica",books:["All of Statistics \u2014 Wasserman","Estatistica Pratica p/ Cientistas de Dados \u2014 Bruce & Bruce","Introduction to Probability \u2014 Blitzstein & Hwang"],items:[
{w:"Probabilidade: axiomas, condicional, independencia, Bayes",s:"probability axioms conditional Bayes, probabilidade condicional Bayes, Bayes theorem",d:"P(A|B)=P(B|A)P(A)/P(B). Independencia: P(A e B)=P(A)*P(B). Bayes: atualizar crencas com evidencia. Spam filter, diagnostico medico."},
{w:"Variaveis aleatorias: discreta, continua, PMF, PDF, CDF",s:"random variables PMF PDF CDF, variaveis aleatorias, probability distributions",d:"Discreta: dado, moeda (PMF). Continua: altura, peso (PDF). CDF: P(X<=x). Esperanca E[X], variancia Var(X). Propriedades de linearidade."},
{w:"Distribuicoes: Bernoulli, Binomial, Poisson, Normal, Exponencial, Uniforme",s:"probability distributions Bernoulli Binomial Poisson Normal, distribuicoes probabilidade",d:"Bernoulli: 1 tentativa (cara/coroa). Binomial: N tentativas. Poisson: eventos raros. Normal: bell curve (CLT!). Exponencial: tempo entre eventos."},
{w:"MLE, MAP, estimadores, viés, variancia, trade-off",s:"MLE MAP estimation, maximum likelihood estimation, bias variance tradeoff",d:"MLE: parametros que maximizam P(dados|theta). MAP: MLE + prior. Vies: erro sistematico. Variancia: erro por ruido. Trade-off: modelo simples (vies alto) vs complexo (variancia alta)."},
{w:"Testes de hipotese: p-valor, intervalo de confianca, CLT",s:"hypothesis testing p-value, teste hipotese p-valor, central limit theorem",d:"H0 (nulo) vs H1 (alternativa). p-valor: probabilidade de ver resultado tao extremo se H0 for verdade. <0.05: rejeitar. CLT: media amostral tende a Normal. IC: range provavel do parametro."}]}]},
{name:"\u{1F527} DevOps & Infra",topics:[
{name:"Docker e Containers",books:["Docker Deep Dive \u2014 Nigel Poulton","The Docker Book \u2014 James Turnbull","Docker in Practice \u2014 Miell & Sayers"],items:[
{w:"O que sao containers: isolamento, imagem vs container, Docker vs VM",s:"what are containers Docker, containers vs VMs, docker explained beginners",d:"Container = processo isolado com suas dependencias. Imagem: template (read-only). Container: instancia rodando. Mais leve que VM (compartilha kernel)."},
{w:"Dockerfile: FROM, RUN, COPY, CMD, EXPOSE, multi-stage",s:"dockerfile tutorial, dockerfile best practices, multi-stage docker build",d:"FROM python:3.12. RUN pip install. COPY . /app. CMD ['python','app.py']. EXPOSE 8000. Multi-stage: build numa imagem, copiar resultado pra imagem menor."},
{w:"Docker Compose: multi-container, volumes, networks",s:"docker compose tutorial, docker compose multi container, docker volumes networks",d:"docker-compose.yml: definir multiplos servicos. volumes: persistir dados. networks: comunicacao entre containers. docker compose up -d."},
{w:"Docker Hub, registries, tags, .dockerignore",s:"docker hub registry, docker image tags, dockerignore file",d:"Docker Hub: repositorio de imagens. docker push/pull. Tags: versoes (app:v1.2, app:latest). .dockerignore: excluir node_modules, .git, .env."}]},
{name:"CI/CD e Cloud",books:["The Phoenix Project \u2014 Gene Kim","Continuous Delivery \u2014 Humble & Farley","AWS Certified Cloud Practitioner \u2014 Piper & Clinton"],items:[
{w:"CI/CD: conceito, pipeline, GitHub Actions",s:"CI CD pipeline tutorial, GitHub Actions workflow, continuous integration delivery",d:"CI: testar automaticamente a cada push. CD: deploy automatico apos testes. GitHub Actions: YAML workflow. Stages: lint > test > build > deploy."},
{w:"Cloud: IaaS, PaaS, SaaS, modelos de pricing",s:"cloud computing IaaS PaaS SaaS, cloud pricing models, AWS vs GCP vs Azure",d:"IaaS: servidor virtual (EC2). PaaS: plataforma gerenciada (Heroku, Railway). SaaS: software pronto (Gmail). Pay-as-you-go. Free tier pra aprender."},
{w:"AWS essenciais: EC2, S3, RDS, Lambda, IAM, VPC",s:"AWS essentials EC2 S3 RDS Lambda, AWS tutorial beginner, AWS IAM VPC",d:"EC2: servidor. S3: storage de arquivos. RDS: banco gerenciado. Lambda: serverless. IAM: permissoes. VPC: rede isolada. Comece pelo free tier!"},
{w:"Deploy: Vercel, Railway, Render, Fly.io",s:"deploy Vercel Railway Render, modern deployment platforms, deploy fullstack app",d:"Vercel: frontend (Next.js). Railway/Render: backend + DB. Fly.io: containers. Todos tem free tier. Conectam com GitHub pra deploy automatico."},
{w:"DNS, dominios, HTTPS, certificados SSL/TLS",s:"DNS domain setup tutorial, HTTPS SSL TLS certificate, how DNS works",d:"DNS: nome > IP. A record, CNAME. Comprar dominio: Namecheap, Cloudflare. HTTPS: Let's Encrypt (gratis). TLS: criptografia em transito."}]},
{name:"Redes pra Devs",books:["Computer Networking \u2014 Kurose & Ross","HTTP: The Definitive Guide \u2014 Gourley & Totty","Redes de Computadores \u2014 Tanenbaum"],items:[
{w:"Modelo OSI e TCP/IP: camadas, protocolos",s:"OSI model TCP IP layers, modelo OSI camadas, networking layers explained",d:"OSI: 7 camadas (fisica > enlace > rede > transporte > sessao > apresentacao > aplicacao). TCP/IP: 4 camadas. Cada camada resolve um problema."},
{w:"TCP vs UDP, portas, sockets",s:"TCP vs UDP difference, network ports sockets, TCP handshake",d:"TCP: confiavel, 3-way handshake (SYN-SYN/ACK-ACK). UDP: rapido, sem garantia (streaming, jogos). Portas: 80(HTTP), 443(HTTPS), 22(SSH), 5432(Postgres)."},
{w:"HTTP/1.1 vs HTTP/2 vs HTTP/3, metodos, headers, cookies",s:"HTTP protocol methods headers, HTTP/2 HTTP/3, HTTP cookies session",d:"GET POST PUT PATCH DELETE. Headers: Content-Type, Authorization, Cache-Control. Cookies: sessao no navegador. HTTP/2: multiplexing. HTTP/3: QUIC/UDP."},
{w:"REST, GraphQL, WebSockets: quando usar cada",s:"REST vs GraphQL vs WebSocket, API protocols comparison, when to use GraphQL",d:"REST: recurso-orientado (maioria). GraphQL: cliente pede exatamente o que quer (mobile). WebSocket: real-time bidirecional (chat, jogos). gRPC: entre servicos."}]}]},
{name:"\u{1F512} Seguranca Basica",topics:[
{name:"Fundamentos de Seguranca",books:["Web App Hacker's Handbook \u2014 Stuttard","Hacking: Art of Exploitation \u2014 Erickson","Serious Cryptography \u2014 Aumasson"],items:[
{w:"CIA Triad: Confidencialidade, Integridade, Disponibilidade",s:"CIA triad cybersecurity, principios seguranca informacao, CIA security fundamentals",d:"Confidencialidade: so quem deve ve. Integridade: dados nao alterados. Disponibilidade: sistema acessivel. Todo controle de seguranca protege pelo menos 1."},
{w:"OWASP Top 10: Injection, XSS, CSRF, Broken Auth",s:"OWASP top 10 explained, SQL injection XSS prevention, OWASP vulnerabilities",d:"SQL Injection: parameterized queries. XSS: sanitizar input/output. CSRF: tokens. Broken Auth: senhas fracas, sessoes mal gerenciadas. Leia owasp.org."},
{w:"Autenticacao vs Autorizacao, sessoes, tokens",s:"authentication vs authorization, session token security, auth security best practices",d:"Autenticacao: quem e voce (login). Autorizacao: o que pode fazer (permissoes). Sessoes: server-side. JWT: stateless token. OAuth2: delegar autenticacao (Login com Google)."},
{w:"Criptografia: hashing (bcrypt/Argon2), simetrica (AES), assimetrica (RSA/ECC)",s:"cryptography hashing encryption, bcrypt Argon2 password hashing, AES RSA encryption",d:"Hash: funcao 1 via (senhas). bcrypt/Argon2: lentas de proposito (dificultar brute force). AES: mesma chave encripta/decripta. RSA/ECC: par chave publica/privada. TLS usa ambas."},
{w:"HTTPS, TLS handshake, certificados, CORS, CSP",s:"TLS handshake explained, HTTPS security, CORS CSP headers security",d:"TLS: cliente e servidor negociam chave simetrica via assimetrica. Certificado: CA confirma identidade. CORS: controle de acesso cross-origin. CSP: prevenir XSS via headers."},
{w:"Principios: minimo privilegio, defesa em profundidade, fail-safe",s:"security principles least privilege defense depth, principios seguranca, security design principles",d:"Minimo privilegio: dar so o necessario. Defesa em profundidade: multiplas camadas. Fail-safe: falha segura (negar acesso se der erro). Security by design."}]}]},
{name:"\u{1F50C} Embarcados & Robotica Intro",topics:[
{name:"Arduino",books:["Arduino Cookbook \u2014 Margolis","Getting Started with Arduino \u2014 Banzi","Make: Electronics \u2014 Charles Platt"],items:[
{w:"Arduino: setup/loop, digitalRead/Write, analogRead/Write",s:"arduino tutorial beginners, arduino setup loop, arduino digital analog",d:"setup(): roda 1 vez. loop(): repete. digitalRead/Write: 0 ou 1. analogRead: 0-1023. analogWrite(PWM): 0-255. Pinos: digitais e analogicos."},
{w:"Sensores: ultrassonico, temperatura (DHT), luz (LDR), PIR, IR",s:"arduino sensors tutorial, sensores arduino, HC-SR04 DHT11 LDR PIR",d:"HC-SR04: distancia. DHT11/22: temperatura+umidade. LDR: luz. PIR: movimento. IR: controle remoto. Cada sensor tem biblioteca propria."},
{w:"Atuadores: LED, motor DC, servo, buzzer, rele",s:"arduino motors servo relay, atuadores arduino, arduino motor driver L298N",d:"LED: output basico. Motor DC: driver L298N/L293D. Servo: angulo preciso. Buzzer: som. Rele: ligar/desligar aparelhos 110V/220V."},
{w:"Comunicacao: Serial (UART), I2C, SPI, displays (LCD, OLED)",s:"arduino serial I2C SPI, arduino LCD OLED display, arduino communication protocols",d:"Serial: debug (Serial.println). I2C: 2 fios, multiplos devices (endereco). SPI: rapido, 4 fios. LCD 16x2. OLED: graficos. Wire.h (I2C), SPI.h."},
{w:"Projeto integrado: estacao meteorologica, robo seguidor de linha",s:"arduino project weather station, arduino line follower robot, arduino project ideas",d:"Estacao: DHT + display + log SD card. Seguidor: sensores IR + motores + PID simples. Exercita: sensores + atuadores + logica + comunicacao."}]},
{name:"ESP32, Raspberry Pi, IoT",books:["Internet of Things with ESP32 \u2014 Kolban","Raspberry Pi Cookbook \u2014 Simon Monk","Programming Robots with ROS \u2014 Quigley"],items:[
{w:"ESP32: WiFi, BLE, deep sleep, MQTT, web server",s:"ESP32 WiFi tutorial, ESP32 MQTT IoT, ESP32 web server project",d:"ESP32: Arduino-compativel + WiFi + BLE. MQTT: protocolo leve pra IoT (pub/sub). Web server: controlar pela rede. Deep sleep: economia de energia."},
{w:"Raspberry Pi: Linux embarcado, GPIO, camera, projetos",s:"raspberry pi tutorial beginners, raspberry pi GPIO python, raspberry pi projects",d:"RPi: computador completo com Linux + GPIO. Python: RPi.GPIO ou gpiozero. Camera module. Projetos: servidor, retro gaming, automacao residencial, NAS."},
{w:"Protocolos IoT: MQTT, HTTP, CoAP, WebSocket",s:"IoT protocols MQTT HTTP CoAP, protocolos IoT, MQTT broker mosquitto",d:"MQTT: leve, pub/sub (broker Mosquitto). HTTP: pesado mas universal. CoAP: REST pra IoT. WebSocket: real-time. Escolha: MQTT pra sensores, HTTP pra APIs."},
{w:"PID control: conceito e implementacao basica",s:"PID control tutorial, controle PID basico, PID controller Arduino",d:"P: proporcional ao erro (reage). I: integral do erro (corrige steady-state). D: derivada do erro (amortece). Tuning: Ziegler-Nichols. Usado em equilibrio de robos, termostatos."}]}]},
{name:"\u{1F3D7}\u{FE0F} Engenharia de Software",topics:[
{name:"Principios, Agile, Patterns",books:["Clean Code \u2014 Robert Martin","The Pragmatic Programmer \u2014 Hunt & Thomas","Software Engineering at Google \u2014 Winters et al."],items:[
{w:"SOLID, DRY, KISS, YAGNI, SoC",s:"SOLID DRY KISS YAGNI principles, principios engenharia software, clean code",d:"S: responsabilidade unica. O: aberto/fechado. L: Liskov. I: segregacao. D: inversao dependencia."},
{w:"Agile, Scrum, Kanban, sprints",s:"agile scrum kanban, metodologia agil, sprint planning retrospective",d:"Sprints 2 semanas. Daily standup. Review. Retrospectiva. User stories."},
{w:"Code review, Design Patterns: Factory, Singleton, Observer, Strategy",s:"design patterns beginners, factory singleton observer, code review best practices",d:"Review: design+logica. Patterns: Factory (criar), Singleton (unico), Observer (eventos), Strategy (trocar algoritmo)."}]}]}
]},
{id:"advanced",name:"\u{1F7E0} AVANCADO",css:"orange",time:"~18-36 meses",desc:"Especializacao e sistemas reais de producao.",areas:[
{name:"\u{1F9E0} Deep Learning",topics:[
{name:"Redes Neurais e Frameworks",books:["Deep Learning \u2014 Goodfellow et al. (gratuito)","Hands-On Machine Learning \u2014 Geron (parte 2)","Deep Learning with Python \u2014 Francois Chollet"],items:[
{w:"Perceptron, MLP, Backpropagation (do zero)",s:"neural network from scratch python, backpropagation explained, MLP tutorial",d:"Neuronio: soma ponderada + ativacao. Forward pass > loss > backward pass. Implemente do zero com NumPy!"},
{w:"PyTorch: tensores, autograd, Dataset, DataLoader, treino",s:"PyTorch tutorial 2025, pytorch tensors autograd, pytorch training loop",d:"torch.tensor, .backward(), nn.Module, DataLoader. GPU: .to('cuda'). Prefira PyTorch a TF."},
{w:"CNNs: convolucao, pooling, ResNet, transfer learning",s:"CNN convolutional neural network, ResNet transfer learning PyTorch, image classification",d:"Conv2d, MaxPool, flatten, FC. ResNet: skip connections. Transfer learning: treinar no seu dado com modelo pre-treinado."},
{w:"RNNs, LSTM, GRU, Sequence-to-Sequence",s:"RNN LSTM GRU tutorial, sequence to sequence, recurrent neural networks",d:"RNN: memoria sequencial. LSTM: resolve vanishing gradient. GRU: LSTM simplificado. Seq2Seq: traducao."},
{w:"Transformers e Attention: o coraoco de tudo moderno",s:"transformer attention mechanism, self-attention explained, attention is all you need",d:"Self-attention: cada token atende todos. Multi-head. Positional encoding. Base de GPT, BERT, tudo moderno."},
{w:"GANs, VAEs, Diffusion Models",s:"GAN tutorial PyTorch, VAE generative model, diffusion models explained",d:"GAN: generator vs discriminator. VAE: latent space. Diffusion: denoise iterativo (Stable Diffusion)."},
{w:"Treinamento: batch norm, dropout, lr scheduling, mixed precision",s:"training tricks deep learning, batch normalization dropout, mixed precision training",d:"BatchNorm, Dropout, LR scheduling (cosine, warmup). Mixed precision (fp16). Gradient clipping."}]},
{name:"NLP",books:["Speech and Language Processing \u2014 Jurafsky & Martin (gratuito)","NLP with Transformers \u2014 Tunstall et al.","Foundations of Statistical NLP \u2014 Manning & Schutze"],items:[
{w:"Tokenizacao, embeddings, Word2Vec, BERT, GPT",s:"NLP tokenization embeddings Word2Vec, BERT GPT explained, NLP fundamentals",d:"Tokenizar: texto>numeros. Embeddings: palavras como vetores. Word2Vec, BERT (bidirecional), GPT (autoregressivo)."},
{w:"Hugging Face Transformers: fine-tuning, pipelines",s:"hugging face transformers tutorial, fine-tuning BERT, HF pipelines NLP",d:"from transformers import pipeline. Fine-tune no seu dataset. Tokenizers. Hub de modelos."},
{w:"Sentiment, NER, summarization, question answering",s:"sentiment analysis NER, text summarization NLP, question answering transformers",d:"Tarefas NLP classicas. Pipeline HF facilita. Fine-tune pra dominio especifico."}]}]},
{name:"\u{1F916} AI Engineering",topics:[
{name:"LLMs, RAG, Agents, APIs",books:["Building LLM Apps \u2014 Valentino Gagliardi","Designing ML Systems \u2014 Chip Huyen","AI Engineering \u2014 Chip Huyen"],items:[
{w:"OpenAI API / Anthropic API: chat, system prompts, streaming",s:"OpenAI API tutorial, Anthropic Claude API, LLM API chat completion",d:"messages: system+user+assistant. Temperature, max_tokens, streaming. Structured outputs. Caching."},
{w:"Prompt Engineering: few-shot, CoT, self-consistency",s:"prompt engineering techniques, chain of thought prompting, few-shot examples",d:"Zero-shot, few-shot, chain-of-thought, self-consistency. System prompt design. Prompt templates."},
{w:"Embeddings e Vector Databases (Pinecone, Chroma, pgvector)",s:"vector database embeddings, Pinecone Chroma pgvector, semantic search",d:"Texto>vetor (OpenAI embeddings, Sentence Transformers). Busca por similaridade. pgvector: Postgres nativo."},
{w:"RAG: Retrieval-Augmented Generation",s:"RAG retrieval augmented generation, RAG tutorial LangChain, RAG architecture",d:"Indexar docs > buscar relevantes > alimentar LLM. Chunks, overlap, re-ranking. Reduz alucinacao."},
{w:"Agents: LangChain, LangGraph, tool use, function calling",s:"LLM agents LangChain LangGraph, function calling OpenAI, AI agent tutorial",d:"Agente: LLM + ferramentas. Decide qual tool usar. ReAct pattern. Multi-step reasoning."},
{w:"Multimodal: vision, audio, video",s:"multimodal AI vision audio, GPT-4V multimodal, whisper speech recognition",d:"GPT-4V: imagem+texto. Whisper: audio>texto. Modelos multimodais unificados."},
{w:"Fine-tuning, LoRA, QLoRA, RLHF, DPO",s:"fine-tuning LLM LoRA QLoRA, RLHF DPO alignment, parameter efficient fine-tuning",d:"Fine-tune: adaptar modelo ao seu dominio. LoRA: eficiente (poucos parametros). RLHF/DPO: alinhar com preferencias humanas."},
{w:"Safety, guardrails, eval, red-teaming",s:"LLM safety guardrails, AI evaluation benchmarks, red teaming LLM",d:"Guardrails: limitar outputs. Eval: metricas automaticas. Red-team: encontrar falhas. Responsible AI."}]}]},
{name:"\u{1F5C4}\u{FE0F} Banco de Dados Avancado",topics:[
{name:"PostgreSQL DBA & NoSQL",books:["PostgreSQL Internals \u2014 Suzuki","Designing Data-Intensive Apps \u2014 Kleppmann","Database Internals \u2014 Alex Petrov"],items:[
{w:"PostgreSQL: Window Functions, CTEs recursivas, PL/pgSQL",s:"PostgreSQL window functions CTE recursive, PL/pgSQL stored procedures",d:"ROW_NUMBER, RANK, LAG, LEAD. WITH RECURSIVE. PL/pgSQL: logica no banco."},
{w:"Indices avancados: GiST, GIN, BRIN, partial, expression",s:"PostgreSQL GiST GIN BRIN index, partial expression index, index optimization",d:"GiST: geometria. GIN: full-text, JSONB. BRIN: dados ordenados. Partial: WHERE. Expression: computed."},
{w:"Replicacao, backup, PITR, PgBouncer, vacuuming",s:"PostgreSQL replication streaming, PgBouncer connection pool, PITR backup",d:"Streaming replication. PgBouncer: pooling. pg_dump, PITR. VACUUM: limpar dead tuples. MVCC."},
{w:"Query optimization: EXPLAIN ANALYZE, planner, statistics",s:"PostgreSQL EXPLAIN ANALYZE, query optimization planner, PostgreSQL performance",d:"EXPLAIN ANALYZE BUFFERS. seq scan vs index scan. Custo estimado vs real. pg_stat_statements."}]}]},
{name:"\u{1F6E1}\u{FE0F} DevSecOps & Seguranca",topics:[
{name:"Security Pipeline, Container Security",books:["DevSecOps \u2014 Jim Bird","Container Security \u2014 Liz Rice","Kubernetes Security \u2014 Karambelkar"],items:[
{w:"SAST, DAST, SCA: seguranca no pipeline CI/CD",s:"SAST DAST SCA security pipeline, DevSecOps CI CD security, shift left security",d:"SAST: codigo estatico (Semgrep, SonarQube). DAST: app rodando (OWASP ZAP). SCA: dependencias (Snyk, Trivy)."},
{w:"Container security: scan imagens, rootless, seccomp, AppArmor",s:"container security Docker, rootless containers, seccomp AppArmor",d:"Scan: Trivy. Rootless. Seccomp: limitar syscalls. Nao rodar como root. Multi-stage builds."},
{w:"SBOM, threat modeling, segredos (Vault)",s:"SBOM supply chain security, threat modeling STRIDE, HashiCorp Vault secrets",d:"SBOM: inventario de componentes. STRIDE: threat model. Vault: gerenciar secrets. Nao hardcode senhas!"},
{w:"Kubernetes security, RBAC, Network Policies, Pod Security",s:"Kubernetes security RBAC, network policies K8s, pod security standards",d:"RBAC: quem pode o que. Network Policies: isolar pods. Pod Security: restringir privilegios."}]}]},
{name:"\u{2601}\u{FE0F} Cloud & Kubernetes",topics:[
{name:"IaC, K8s, Observabilidade",books:["Kubernetes Up and Running \u2014 Burns et al.","Terraform Up and Running \u2014 Brikman","Site Reliability Engineering \u2014 Google (gratuito)"],items:[
{w:"Kubernetes: pods, services, deployments, ingress, helm",s:"kubernetes tutorial 2025, K8s pods services deployments, helm charts",d:"Pod: menor unidade. Service: expor. Deployment: declarativo. Ingress: roteamento. Helm: pacotes."},
{w:"IaC: Terraform, Ansible, GitOps (ArgoCD/Flux)",s:"terraform tutorial, ansible infrastructure, GitOps ArgoCD Flux",d:"Terraform: infra como codigo (HCL). Ansible: configuracao. GitOps: git como fonte de verdade."},
{w:"Observabilidade: Prometheus, Grafana, ELK/Loki, tracing",s:"prometheus grafana monitoring, ELK stack logging, distributed tracing",d:"Metricas (Prometheus), Logs (Loki/ELK), Traces (Jaeger/Tempo). Alertas. Dashboards Grafana."},
{w:"Cloud avancado: VPC, IAM, Load Balancers, auto-scaling",s:"AWS VPC IAM tutorial, cloud networking, auto scaling load balancer",d:"VPC: rede isolada. IAM: permissoes granulares. ALB/NLB. Auto-scaling groups."}]}]},
{name:"\u{1F50C} Robotica & IoT",topics:[
{name:"ROS, Visao, Controle",books:["Programming Robots with ROS \u2014 Quigley et al.","Robotics Vision & Control \u2014 Peter Corke","Introduction to Autonomous Robots \u2014 Correll (gratuito)"],items:[
{w:"ROS2: nodes, topics, services, actions, launch",s:"ROS2 tutorial 2025, ROS2 nodes topics services, robot operating system",d:"ROS2: framework padrao. Nodes: processos. Topics: pub/sub. Services: req/res. Actions: longa duracao."},
{w:"Visao computacional: OpenCV, deteccao, tracking",s:"OpenCV python tutorial, computer vision detection tracking, image processing",d:"OpenCV: captura, filtros, deteccao de bordas/faces. YOLO: object detection real-time."},
{w:"Cinematica, SLAM, sensores (LIDAR, IMU, cameras)",s:"robot kinematics SLAM, LIDAR IMU sensor fusion, autonomous navigation",d:"Cinematica: geometria do movimento. SLAM: mapear+localizar. Sensor fusion: combinar dados."},
{w:"Controle: PID avancado, MPC, path planning (A*, RRT)",s:"PID controller advanced, MPC model predictive control, path planning A* RRT",d:"PID: tuning. MPC: otimizacao com modelo. A*/RRT: planejamento de caminho."}]}]},
{name:"\u{1F3D7}\u{FE0F} Arquitetura de Software",topics:[
{name:"System Design",books:["System Design Interview \u2014 Alex Xu","Designing Data-Intensive Apps \u2014 Kleppmann","Clean Architecture \u2014 Robert Martin"],items:[
{w:"Microservices, monolito, event-driven, CQRS",s:"microservices vs monolith, event driven architecture, CQRS event sourcing",d:"Monolito: simples pra comecar. Micro: escala independente. Event-driven: desacoplado. CQRS: leitura/escrita separadas."},
{w:"Message queues: Kafka, RabbitMQ, Redis Pub/Sub",s:"message queue Kafka RabbitMQ, event streaming, async communication",d:"Kafka: streaming de eventos. RabbitMQ: filas tradicionais. Desacoplar servicos. Resiliencia."},
{w:"Caching, CDN, Load Balancing, Rate Limiting",s:"caching strategies CDN, load balancing algorithms, rate limiting API",d:"Redis/Memcached. CDN: distribuir estaticos. LB: round-robin, least-connections. Rate limit: proteger API."},
{w:"Design Patterns avancados: Repository, UoW, Mediator, Saga",s:"advanced design patterns, repository pattern, saga pattern distributed",d:"Repository: abstrair dados. UoW: transacao. Mediator: desacoplar. Saga: transacoes distribuidas."}]}]}
]},
{id:"expert",name:"\u{1F534} MUITO AVANCADO",css:"red",time:"Continuo",desc:"MLOps, pesquisa, lideranca, seguranca ofensiva. Carreira senior+.",areas:[
{name:"\u{2699}\u{FE0F} MLOps & Producao",topics:[
{name:"Pipeline ML em Producao",books:["Designing ML Systems \u2014 Chip Huyen","MLOps \u2014 Kreuzberger et al.","Building ML Powered Apps \u2014 Ameisen"],items:[
{w:"MLflow, Weights & Biases: experiment tracking",s:"MLflow W&B experiment tracking, ML experiment management, model registry",d:"Track: metricas, parametros, artefatos. Compare runs. Model registry. Reproducibilidade."},
{w:"Feature Stores, Data Pipelines (Airflow, dbt)",s:"feature store ML, Apache Airflow dbt, ML data pipeline",d:"Feature store: features reutilizaveis. Airflow: orquestrar. dbt: transformar dados."},
{w:"Model Serving: TorchServe, Triton, BentoML, endpoints",s:"model serving TorchServe Triton, ML model deployment, inference optimization",d:"REST/gRPC endpoint. Batching. GPU inference. Quantizacao (INT8). ONNX Runtime."},
{w:"Monitoring: data drift, model drift, A/B testing",s:"ML model monitoring drift detection, A/B testing ML, model performance monitoring",d:"Data drift: distribuicao mudou. Model drift: performance caiu. A/B: comparar modelos. Retrain triggers."},
{w:"CI/CD para ML, testes de modelo, reproducibilidade",s:"ML CI CD pipeline, ML testing, reproducibility machine learning",d:"Testar dados, modelo, pipeline. DVC: versionar dados. Docker + pipeline = reproduzivel."}]}]},
{name:"\u{1F9EC} Pesquisa & Fronteira",topics:[
{name:"RL, Multimodal, Scaling Laws",books:["Reinforcement Learning \u2014 Sutton & Barto (gratuito)","Deep RL Hands-On \u2014 Maxim Lapan","The Alignment Problem \u2014 Brian Christian"],items:[
{w:"Reinforcement Learning: MDP, Q-Learning, PPO, GRPO",s:"reinforcement learning PPO Q-learning, RL tutorial, deep reinforcement learning",d:"MDP: estado-acao-recompensa. Q-Learning: tabular. DQN, PPO, GRPO. Ambientes: Gymnasium."},
{w:"Multimodal: CLIP, LLaVA, modelos unificados",s:"multimodal AI CLIP LLaVA, vision language models, multimodal learning",d:"CLIP: imagem+texto embeddings. LLaVA: VLM. Modelos gerais que entendem multiplas modalidades."},
{w:"Scaling Laws, Mixture of Experts, Sparse Models",s:"scaling laws LLM, mixture of experts MoE, sparse models efficiency",d:"Mais dados + mais parametros = melhor (ate certo ponto). MoE: ativar subset. Eficiencia."},
{w:"Ler papers: arXiv, Papers With Code, conferencias",s:"how to read ML papers, arXiv ML, Papers With Code, NeurIPS ICML",d:"arXiv: pre-prints. PWC: papers+codigo. Conferencias: NeurIPS, ICML, ICLR, CVPR, ACL. Leia 1 paper/semana."},
{w:"AI Safety, Alignment, Interpretability",s:"AI safety alignment, mechanistic interpretability, AI ethics",d:"Alignment: IA fazendo o que queremos. Interpretability: entender COMO decide. Safety: prevenir riscos."}]}]},
{name:"\u{1F6E1}\u{FE0F} Cyber Security Avancado",topics:[
{name:"Pentest, Forense, Red/Blue Team",books:["Penetration Testing \u2014 Georgia Weidman","The Web App Hacker's Handbook \u2014 Stuttard","Blue Team Handbook \u2014 Alan White"],items:[
{w:"Pentest: recon, scanning, exploitation, post-exploitation, reporting",s:"penetration testing methodology, ethical hacking tutorial, pentest phases",d:"Recon > Scan (nmap) > Exploit (Metasploit) > Post-exploit > Report. Bug bounty: HackerOne, Bugcrowd."},
{w:"Forense digital, malware analysis, incident response",s:"digital forensics, malware analysis, incident response DFIR",d:"Volatility: memoria. Wireshark: rede. Analise de malware em sandbox. IR: conter, erradicar, recuperar."},
{w:"Red Team vs Blue Team, MITRE ATT&CK, SOC",s:"red team blue team, MITRE ATT&CK framework, SOC security operations",d:"Red: atacar. Blue: defender. Purple: colaborar. MITRE: framework de taticas. SOC: monitorar 24/7."},
{w:"Certificacoes: CompTIA Security+, CEH, OSCP",s:"security certifications CompTIA CEH OSCP, cybersecurity career path",d:"Security+: fundacao. CEH: ethical hacking. OSCP: hands-on pentest (gold standard)."}]}]},
{name:"\u{1F4BC} Lideranca & Gestao",topics:[
{name:"Product & Engineering Management",books:["Engineering Manager \u2014 Camille Fournier","Inspired \u2014 Marty Cagan","Team Topologies \u2014 Skelton & Pais"],items:[
{w:"Product Discovery, priorizacao, roadmap, metricas",s:"product discovery techniques, product roadmap prioritization, product metrics OKR",d:"Discovery: entrevistar usuarios. Priorizacao: RICE, MoSCoW. OKRs. Metricas: MAU, retention, NPS."},
{w:"1:1s, feedback, coaching, hiring, demissao",s:"engineering manager 1on1, giving feedback, technical hiring interview",d:"1:1 semanal. Feedback: SBI (Situacao-Comportamento-Impacto). Coaching > telling. Hiring: pair programming."},
{w:"Team Topologies, postmortems, cultura de engenharia",s:"team topologies, blameless postmortems, engineering culture",d:"Stream-aligned, platform, enabling, complicated-subsystem. Postmortem blameless. Cultura: safety psicologica."},
{w:"Comunicacao tecnica, ADRs, RFCs, documentacao",s:"architecture decision records, RFC engineering, technical writing",d:"ADR: registrar decisoes. RFC: propor mudancas. Docs: escrever pra quem nao tem contexto."}]}]},
{name:"\u{1F680} Sistemas Distribuidos",topics:[
{name:"Teoria e Pratica",books:["Designing Data-Intensive Apps \u2014 Kleppmann","Distributed Systems \u2014 Maarten van Steen","Understanding Distributed Systems \u2014 Vitillo"],items:[
{w:"CAP, PACELC, consenso (Raft/Paxos), consistencia eventual",s:"CAP theorem PACELC, Raft Paxos consensus, eventual consistency",d:"CAP: Consistency vs Availability em particao. Raft: consenso pratico. Eventual consistency."},
{w:"Escalabilidade: sharding, partitioning, replicacao",s:"database sharding partitioning, horizontal scaling, data replication strategies",d:"Shard: dividir dados. Replica: copiar. Horizontal: mais maquinas. Vertical: maquina maior."},
{w:"Tolerancia a falhas, circuit breaker, retry, idempotencia",s:"fault tolerance distributed systems, circuit breaker pattern, idempotency",d:"Circuit breaker: parar de chamar servico com falha. Retry com backoff. Idempotencia: mesma chamada = mesmo efeito."},
{w:"gRPC, Protocol Buffers, service mesh (Istio)",s:"gRPC protocol buffers, service mesh Istio, microservices communication",d:"gRPC: rapido, tipado. Protobuf: serializacao eficiente. Service mesh: observabilidade entre servicos."}]}]}
]}
];

