// Final level data — desafios finais (capstone) por nível + capstone da trilha Game Design.
const FINAL_LEVEL = {
  "green": {
    "project": {
      "title": "🏆 DESAFIO FINAL — Meu Primeiro App de Dados",
      "desc": "Seu primeiro projeto REAL: uma aplicação Python que coleta, guarda e mostra dados na web, integrando as habilidades centrais das 13 áreas do nível.\n• Escolha um domínio de dados que te motive (ex.: hábitos/finanças pessoais, coleção/catálogo, medições de um sensor ou experimento, notas de estudo) — se curte IA/dados, priorize um tema com números que dê pra analisar\n• Modele e persista os dados em um banco (SQLite): defina tabelas, escreva as queries de CRUD e valide as entradas\n• Estruture o código em Python com funções e módulos separados (lógica, acesso a dados, interface) — nada de um script gigante\n• Dê uma cara web: uma página HTML/CSS que lista e cadastra registros, servida por um backend simples (Flask/FastAPI)\n• Aplique matemática e estatística de verdade sobre os dados: média, mediana, desvio-padrão e uma probabilidade/contagem que faça sentido no seu tema, exibindo os resultados na tela\n• Trabalhe como dev de verdade: repositório no GitHub com commits incrementais, README explicando como rodar, e o terminal/SO para instalar dependências e executar o app\n• Escreva uma retrospectiva curta (meta-habilidade): o que travou, como você aprendeu a destravar e o que faria diferente",
      "deliverable": "Repositório público no GitHub contendo: (1) app Python rodável (README com passo a passo de instalação e execução no terminal), organizado em módulos; (2) banco SQLite com esquema versionado e operações de CRUD funcionando pela interface; (3) front-end web (HTML/CSS) que lista, cadastra e edita registros via backend Flask/FastAPI; (4) uma tela ou seção de 'estatísticas' mostrando ao menos média, mediana, desvio-padrão e uma métrica de probabilidade/contagem calculadas a partir dos dados reais; (5) histórico de commits incrementais e um RETRO.md com a retrospectiva de aprendizagem."
    }
  },
  "yellow": {
    "project": {
      "title": "🏆 DESAFIO FINAL — Sistema Full-Stack com Motor de Dados/IA",
      "desc": "As 28 áreas do nível intermediário te deram um leque enorme: você já pensa em estruturas de dados e complexidade, programa OOP em Python (além de C/Rust, Java ou Go), entende SO, redes, concorrência, bancos de dados e o ciclo de engenharia de software — e teve a primeira imersão em matemática p/ ML, IA/ML e análise de dados. Chegou a hora de mostrar que essas peças se combinam num produto real de nível júnior/pleno.\n\nConstrua uma aplicação end-to-end que ingere dados, faz um processamento inteligente e entrega valor por uma interface real. Você NÃO precisa usar as 28 áreas — o objetivo é integrar as habilidades centrais de forma coerente. Escolha UM domínio de foco e trate os demais como camadas de apoio:\n\n• 🤖 Dados/IA (recomendado, alinhado ao seu foco): pipeline que coleta e limpa dados (pandas/R), treina/aplica um modelo de ML supervisionado ou não-supervisionado com métricas honestas (train/test, baseline, avaliação) e expõe previsões via API + dashboard.\n• 🌐 Full-Stack: app com back-end (API REST, autenticação, camada de dados) e front-end, com um recurso de dados/analytics embutido para dar peso ao seu foco.\n• 🖥️ Sistemas: serviço de baixo nível em C/Rust/Go explorando concorrência/paralelismo (threads, canais, sincronização) — ex.: crawler concorrente, mini-servidor HTTP ou processador de logs — com benchmarks reais.\n• 🔒 Segurança: ferramenta ou serviço com modelagem de ameaças, autenticação/autorização corretas, validação de entrada e um scanner/análise simples, documentando as vulnerabilidades tratadas.\n\nQualquer que seja o foco, o sistema deve ter: modelagem de dados e um banco (BD Intermediário — schema normalizado, queries, índices); design orientado a objetos e/ou modular limpo; concorrência ou assíncrono onde fizer sentido; testes automatizados; versionamento em Git com histórico legível; e empacotamento reprodutível (Docker/DevOps básico). Trate complexidade de algoritmos e corretude como cidadãos de primeira classe.",
      "deliverable": "Repositório Git público com uma aplicação end-to-end funcional no domínio escolhido, contendo: (1) código organizado em camadas (dados, lógica/negócio ou modelo, interface/API) com OOP ou design modular claro; (2) persistência em banco de dados com schema documentado e migrações ou script de setup; (3) para foco Dados/IA, um notebook ou módulo de treino com EDA, baseline, modelo e métricas de avaliação reportadas (accuracy/F1/RMSE conforme o problema) + endpoint/dashboard que serve as previsões; (4) suíte de testes automatizados passando em CI (GitHub Actions) e cobertura das partes críticas; (5) Dockerfile/docker-compose que sobe o sistema com um comando; (6) README com arquitetura (diagrama), decisões de design, trade-offs de complexidade/desempenho, como rodar e limitações conhecidas; (7) histórico de commits incremental e legível. Bônus: deploy acessível por URL pública e um benchmark ou análise de desempenho medindo o efeito da concorrência/índices/otimizações escolhidas."
    }
  },
  "orange": {
    "project": {
      "title": "🏆 DESAFIO FINAL: Sistema Avançado de Ponta a Ponta",
      "desc": "As 29 áreas deste nível cobrem IA profunda, dados, infra, segurança e hardware — ninguém constrói tudo num projeto só. Escolha UM domínio-foco e projete um sistema de nível profissional que integre as habilidades centrais desse eixo, com rigor de engenharia (arquitetura, dados, deploy e avaliação).\n\n• Escolha seu domínio (foco pessoal em IA/Dados tem peso — mas todos são válidos):\n  → IA/Dados: pipeline de Data Engineering alimentando um modelo de Deep Learning (NLP, Visão Computacional, RecSys, Séries Temporais ou RL), servido como produto de AI Engineering com RAG sobre Vector DB e método de Data Science para avaliar (baselines, métricas honestas, experimentação/ablação).\n  → Segurança: plataforma que combine Criptografia Aplicada, Ethical Hacking (web/redes) e DevSecOps, ou um lab de Análise de Malware/Engenharia Reversa com trilha forense.\n  → Sistemas/Infra: serviço distribuído sobre Cloud & Kubernetes com Banco de Dados Avançado, observabilidade e Arquitetura de Software bem justificada.\n  → Nichos aplicados: Robótica/IoT, Sistemas de Controle, AR/VR/XR, Finanças Quantitativas/Fintech, Bioinformática, Blockchain/Web3 ou Otimização & Pesquisa Operacional — sempre com um núcleo técnico avançado real.\n\n• Requisitos transversais (valem para qualquer domínio):\n  → Arquitetura documentada: diagrama, decisões (ADRs) e justificativa de trade-offs.\n  → Dados de verdade: ingestão/versão de dados ou datasets reais; nada de toy data mascarado de produção.\n  → Deploy reprodutível: containerizado, com CI/CD e infra como código (K8s/Cloud onde couber).\n  → Avaliação crítica: métricas, testes e uma análise honesta do que NÃO funcionou.\n\n• Não force jogos: Game AI, Áudio de Jogos e Game Dev Avançado têm capstone próprio na trilha de Game Design — só entram aqui se o SEU domínio escolhido for jogos.\n\n• Pense como sênior: escopo defensável, escolhas de ferramenta (Python/Julia/etc.) justificadas e um sistema que você teria orgulho de mostrar num portfólio ou entrevista.",
      "deliverable": "Repositório público de um sistema avançado ponta a ponta no domínio escolhido, contendo: (1) README com o problema, o domínio escolhido e a arquitetura (diagrama + ADRs de trade-offs); (2) código versionado com pipeline de dados/ingestão reprodutível e testes; (3) deploy funcional containerizado com CI/CD e IaC (ou instruções verificáveis de execução em Cloud/K8s quando aplicável); (4) para foco IA/Dados: modelo treinado + serviço de inferência (API/RAG sobre Vector DB) e um relatório de avaliação com baselines, métricas e ablações; (5) um post-mortem curto (1-2 páginas) analisando resultados, limitações e o que faria diferente. Deve rodar a partir do zero seguindo o README, com demo (link, vídeo ou screenshots) comprovando o funcionamento."
    }
  },
  "red": {
    "project": {
      "title": "🏆 DESAFIO FINAL — Plataforma de ML Distribuída em Produção, Segura por Design e Validada em Guerra Cibernética",
      "desc": "Capstone sênior que integra os 6 pilares do nível (Sistemas Distribuídos, MLOps & Produção, Pesquisa & Fronteira, Blue Team/Defesa & Forense, Exploitation/SOC/Purple Team e Red Team) numa única entrega profissional coerente: um serviço de ML distribuído, resiliente e defensável de ponta a ponta — do treino ao inference — colocado à prova por um exercício adversarial completo (Red vs. Blue, fechado via Purple Team).\n\n• Sistemas Distribuídos: projete e opere o serviço em múltiplos nós/regiões com tolerância a falhas — replicação, coordenação (quorum ou leader election), particionamento, backpressure e degradação graciosa; comprove com um teste de caos (matar nós, injetar latência, partição de rede) mantendo o SLO.\n• MLOps & Produção: pipeline reprodutível com versionamento de dados/modelo, CI/CD de modelo, registry, deploy canário ou blue-green, monitoramento de drift e de performance, rollback automático e observabilidade (métricas, logs, tracing).\n• Pesquisa & Fronteira: incorpore uma contribuição de fronteira — reproduza criticamente um paper recente e adapte a técnica ao seu domínio (ex.: LLM/RAG, otimização de inference, aprendizado eficiente ou robustez adversarial), com ablação e comparação honesta contra baseline.\n• Blue Team / Defesa & Forense: trate a própria plataforma como alvo — threat model, hardening, logging de segurança, detecção (SIEM/EDR ou equivalente), plano de resposta a incidentes e coleta forense com cadeia de custódia sobre um incidente simulado.\n• Exploitation, SOC & Purple Team: monte a operação de SOC (playbooks e detecções mapeadas ao MITRE ATT&CK) e conduza um ciclo Purple Team — atacantes e defensores compartilhando TTPs para fechar lacunas de detecção de forma iterativa.\n• Red Team & Adversary Simulation: execute uma simulação adversarial com escopo definido (kill chain, movimentação lateral e ataques específicos de ML — data poisoning, evasão do modelo, model/prompt injection ou extração), documentando impacto real e o que a defesa detectou.\n\nFoco pessoal: se o seu interesse é IA e dados, faça do componente de ML/pesquisa o coração do sistema e da segurança de ML (ataques ao modelo) o eixo do exercício adversarial — mas os seis pilares devem aparecer de forma verificável.",
      "deliverable": "Um repositório de nível produção contendo: (1) o serviço de ML distribuído rodando em múltiplos nós/regiões com Infraestrutura-como-Código e um relatório de teste de caos comprovando o SLO sob falha; (2) o pipeline de MLOps ponta a ponta (dados/modelo versionados, CI/CD, registry, deploy canário/blue-green, dashboards de drift/performance e rollback automático demonstrado); (3) um mini-paper (6–10 páginas) da contribuição de fronteira com ablação, baseline e código reprodutível; (4) um dossiê de segurança com threat model, arquitetura de detecção mapeada ao MITRE ATT&CK, playbooks de SOC e plano de resposta a incidentes; (5) um relatório de exercício adversarial (Red Team report com kill chain e ataques de ML + Blue Team com timeline forense e cadeia de custódia + matriz Purple Team de lacunas fechadas antes/depois); e (6) um architecture decision record (ADR) e um vídeo/demo de 10–15 min defendendo as decisões de arquitetura, produção, pesquisa e postura de segurança ofensiva e defensiva."
    }
  },
  "blue": {
    "project": {
      "title": "🏆 DESAFIO FINAL: Do Problema ao Paper Reproduzível",
      "desc": "As 5 áreas deste nível (Escrita/Metodologia Científica, IC, Mestrado, Doutorado e Ferramentas Acadêmicas) só fecham quando você conduz uma pesquisa de ponta a ponta: da pergunta ao artefato revisável. Escolha um tema de pesquisa REAL e delimitado (recomendado: algo em IA/dados — ex.: avaliar uma técnica de ML, replicar um baseline recente, analisar um dataset público — mas vale qualquer domínio da sua trilha).\n\n• Formule o problema como cientista: revisão de literatura mínima (Scholar/arXiv/Zotero), lacuna identificada, pergunta e hipótese falseável (Metodologia Científica).\n• Desenhe o método com rigor de IC/Mestrado: variáveis, dataset/coleta, protocolo experimental, baseline e métricas definidos ANTES de rodar; controle de vieses e ética.\n• Execute e analise: experimento reproduzível com seed fixa, ambiente versionado e teste estatístico honesto (significância, intervalo de confiança, tamanho de efeito) — sem p-hacking.\n• Escreva no padrão acadêmico (nível Doutorado): paper em LaTeX/Overleaf com Abstract, Introdução, Trabalhos Relacionados, Método, Resultados, Discussão de limitações e Referências (BibTeX).\n• Domine as Ferramentas Acadêmicas: Git para o código, notebook/script determinístico, gerenciador de referências e um repositório público que qualquer pessoa clona e reproduz do zero.\n• Feche o ciclo: prepare uma defesa curta (slides + 5 min) antecipando as perguntas mais duras de uma banca.",
      "deliverable": "Um repositório público (GitHub) contendo: (1) o paper em PDF gerado a partir de fonte LaTeX (com .bib), 6-12 páginas, no formato de uma conferência/journal real (ex.: IEEE/ACM); (2) todo o código e dados (ou script de download) com README de reprodução — um comando/notebook que, com seed fixa e ambiente declarado (requirements/environment), regenera TODAS as figuras e tabelas do paper; (3) os resultados com análise estatística explícita (não só a média). Critério de aceite: um terceiro clona o repo e reproduz os números-chave do paper sem contato com você. Bônus: submeter a um evento estudantil, workshop, SBC ou preprint (arXiv/OSF)."
    }
  },
  "purple": {
    "project": {
      "title": "🏆 DESAFIO FINAL — Do Dossiê de Carreira à Contribuição Open Source Real",
      "desc": "Integre as 6 áreas do nível (Aprendizado & Preparação de Carreira, Trilhas/Crescimento/Transições, Liderança & Gestão de Pessoas, Liderança Técnica, Produto/Estratégia & Negócio, Open Source na Prática) em um único projeto que prova sua prontidão para liderar — não só codar.\n\n• Diagnóstico & rota: mapeie onde você está hoje vs. a trilha-alvo (IC/junior→pleno→sênior→staff/EM ou fundador), escolhendo UM foco de domínio para ancorar as decisões (recomendado: IA/Dados; alternativas: web, sistemas ou segurança). Justifique a transição com um plano de aprendizado de 6-12 meses e metas mensuráveis.\n• Marca & preparação: CV orientado a impacto, LinkedIn/portfólio e uma narrativa de carreira coerente; prepare-se para entrevistas do foco escolhido (system design + comportamental/STAR) com um banco próprio de perguntas e respostas.\n• Lente de produto & negócio: pegue um problema real (idealmente de dados/IA) e escreva um mini one-pager — hipótese, métrica de sucesso, custo/impacto e trade-offs de decisão — mostrando que você pensa como dono, não só como executor.\n• Liderança técnica: produza um artefato de liderança real — um RFC/ADR ou tech design que defenda uma decisão de arquitetura com alternativas, riscos e plano de rollout.\n• Liderança de pessoas: escreva um guia curto de mentoria/1:1 e dê feedback estruturado (ex.: SBI) a alguém em um code review ou par de estudo, registrando o antes/depois.\n• Open source de verdade: contribua para um projeto público ativo (issue → discussão → PR mergeado ou em review sério), preferindo o ecossistema do seu foco (ex.: libs de ML/dados). Documente o ciclo completo: escopo, negociação com maintainers e resposta a revisão.",
      "deliverable": "Um repositório público \"dossiê de carreira\" contendo: (1) plano de trilha/transição de 6-12 meses com foco de domínio escolhido e metas mensuráveis; (2) CV + link de LinkedIn/portfólio atualizados e um banco de ≥10 pares de perguntas/respostas de entrevista (técnica + comportamental) do foco; (3) um one-pager de produto/negócio de um problema real com métrica de sucesso e trade-offs; (4) um RFC/ADR de decisão técnica com alternativas, riscos e rollout; (5) um guia de mentoria/1:1 + um registro de feedback estruturado (SBI) real dado a alguém; e (6) o link de UMA contribuição open source rastreável a um projeto ativo (issue + PR mergeado ou em review), com um pós-mortem de meia página do ciclo. Verificável por: repositório público navegável, PR/issue linkáveis no GitHub e artefatos (RFC, one-pager, plano) revisáveis por terceiros."
    }
  },
  "gamedesign": {
    "track": true,
    "project": {
      "title": "🏆 Capstone da Trilha — Um Jogo Completo e Lançado",
      "desc": "O único capstone em que o desafio É sobre jogos: prove as 7 partes da Trilha de Game Design (Fundamentos → Teoria & Sistemas → Arte/Narrativa/Tabuleiro → Programação & Engines → Game AI → Áudio & Arte Técnica → Dev Avançado) num único jogo pequeno em escopo, polido e de fato LANÇADO. Corte sem dó: um jogo pequeno terminado vale mais que um épico inacabado.\n\n• Design (MDA): visão clara com core loop, mecânicas → dinâmicas → estética/emoção; curva de dificuldade e pacing intencionais; sistemas balanceados (economia, combate, progressão).\n• Níveis e narrativa: níveis projetados de propósito (blockout antes da arte, guiar o olhar, ensinar sem tutorial) com narrativa integrada à jogabilidade e world building coeso.\n• Arte, áudio e game feel: direção de arte e UX consistentes, sound design com middleware (SFX/música reativa) e ao menos um shader próprio; juice/feedback que dá peso às ações.\n• Programação & engines: arquitetura com padrões (ECS/componentes, state machine, object pooling), física e colisão (AABB/SAT), save system com serialização e write atômico.\n• Game AI: inimigos com behavior tree + blackboard (ou FSM/utility AI) e pathfinding (A*), telegrafando ataques — desafiar sem frustrar.\n• Geração procedural: PCG para rejogabilidade — ruído Perlin/Simplex, dungeons (BSP/drunkard walk/autômatos celulares) ou Wave Function Collapse, tudo por seed reprodutível.\n• Produção & lançamento: vertical slice → alpha → beta → gold, playtesting estruturado (observar calado + telemetria) com rebalanceamento por dados, e lançamento público (itch.io/Steam) com página de loja, trailer, press kit e devlog.\n\nOpcional analógico (o dono curte MTG/Pokémon TCG): em vez do digital, entregue um jogo de tabuleiro/cartas completo, print-and-play e comprovadamente balanceado — mesma exigência de MDA, sistemas emergentes, componentes claros, playtesting com métricas e documentação de design.",
      "deliverable": "Um jogo completo e LANÇADO — digital publicado (página de loja + trailer + build jogável em itch.io/Steam) OU de tabuleiro/cartas print-and-play jogável e balanceado — que integre design intencional (MDA), níveis/narrativa, arte+áudio+shader, sistemas avançados (ECS, IA de inimigos com behavior tree/pathfinding, PCG por seed) e produção real, acompanhado de um GDD completo, evidências de playtesting/telemetria com o balanceamento ajustado por dados, e um postmortem honesto que conecte as 7 partes da trilha"
    }
  }
};
