// Final level data
const FINAL_LEVEL = {};

FINAL_LEVEL["green"] = {
  project: {
    title: "🏆 Projeto Final do Iniciante: Plataforma de Estudos Integrada",
    desc: "Construa plataforma de estudos que integra TODAS as 8 áreas do Iniciante:\n\n• Fundamentos: página explicando boot process, binário, RGB/hex, 32 vs 64-bit, open source (com diagramas)\n• SO & Terminal: script shell que automatiza setup (cria pastas, git init, configura venv). Usar chmod pra definir permissões. SSH config pra acessar servidor remoto\n• Python: backend em Python com type hints em todas funções. Usar venv + requirements.txt. Debugging com pdb documentado. Validação de input com regex. Persistência em JSON\n• Matemática: módulo que calcula estatísticas de notas usando somatório (Σ), compara algoritmos por Big O (fibonacci recursivo vs iterativo com timing). Gráficos ASCII no terminal\n• Física: calculadora de fórmulas (F=ma, V=IR, P=VI, kWh), quiz de semicondutores MOSFET\n• Web: frontend HTML+CSS responsivo (media queries mobile-first) + JavaScript com DOM manipulation (querySelector, addEventListener). Dark mode com localStorage. Deploy no GitHub Pages\n• BD: SQLite com tabelas (matérias, notas, metas). Queries GROUP BY + HAVING + agregações. Modelagem ER documentada. Backup com .dump\n• Eletrônica: Arduino lê sensor e envia via serial (UART). Python recebe com pyserial. LED muda cor pela nota média. Montado em protoboard, verificado com multímetro",
    deliverable: "Repositório GitHub com: site responsivo com localStorage, backend Python com venv+type hints+regex, SQLite com GROUP BY, scripts shell com chmod+SSH, Arduino com serial, gráficos ASCII, modelagem ER, backup .dump, tudo documentado"
  }
};

FINAL_LEVEL["yellow"] = {
  project: {
    title: "🏆 Projeto Final do Intermediário: Plataforma de Gestão de Projetos",
    desc: "Construa plataforma de gestão de projetos integrando as 20 áreas:\n\n• Estruturas de Dados & Algoritmos: Kanban com filas de prioridade e busca eficiente\n• Python Intermediário & OOP: backend FastAPI com SOLID, decorators para auth\n• C, C++ & Rust: CLI em Rust que analisa logs e gera relatório\n• Java & Ecossistema JVM: microsserviço Spring Boot de notificações com JPA\n• Sistemas Operacionais: monitorar processos e limites de memória do servidor\n• Arquitetura de Computadores: otimizar queries pensando em cache locality\n• Concorrência e Paralelismo: WebSocket pra atualizações em tempo real entre usuários\n• Engenharia de Software: TDD 80%+ coverage, CI/CD GitHub Actions, documentação Diátaxis\n• Teoria da Computação & Compiladores: mini DSL pra filtros avançados de tarefas\n• Matemática p/ ML: burndown chart com regressão linear e previsão de conclusão\n• Sinais e Sistemas: alerta sonoro via Web Audio API com frequência customizada\n• Introdução a IA & ML: classificador de prioridade com TF-IDF + scikit-learn\n• Full-Stack: React+TypeScript+Next.js frontend, FastAPI backend, PostgreSQL, JWT\n• Computação Gráfica: Gantt interativo renderizado com SVG e JavaScript\n• Desenvolvimento Mobile: app React Native com visualização e criação de tarefas\n• DevOps & Infra: Docker Compose (app+banco+redis), health checks, Prometheus\n• Go (Golang): worker em Go com goroutines pra jobs pesados (PDF, CSV export)\n• Redes de Computadores: HTTPS/TLS, DNS, firewall rules, reverse proxy Nginx\n• Segurança & Ethical Hacking: rate limiting, input validation, CORS, CSP, OWASP compliance\n• Embarcados & Automação: botão ESP32 que marca tarefa concluída via serial",
    deliverable: "Monorepo: frontend React, backend FastAPI, microsserviço Spring Boot, worker Go, app React Native, CLI Rust, firmware ESP32, Docker Compose, CI/CD, testes 80%+"
  }
};

FINAL_LEVEL["orange"] = {
  project: {
    title: "🏆 Projeto Final do Avançado: Plataforma de Análise Genômica com IA",
    desc: "Construa sistema de análise de segurança integrando as 12 áreas:\n\n• Arquitetura de Software: design de sistema distribuído com diagramas C4\n• Deep Learning: modelo de detecção de anomalias em logs com autoencoder\n• AI Engineering: pipeline RAG com vector database pra buscar documentação de segurança\n• Bioinformática: módulo que analisa sequência genômica FASTA com BioPython\n• Banco de Dados Avançado: PostgreSQL tunado com particionamento e índices otimizados\n• Data Engineering: pipeline ETL com dbt que transforma logs brutos em tabelas analíticas\n• Blockchain & Web3: smart contract de audit trail imutável para registros de segurança\n• Cloud & Kubernetes: deploy em K8s com Helm charts, auto-scaling, monitoring\n• DevSecOps: SAST/DAST no CI/CD, dependency scanning, container scanning\n• Ethical Hacking: módulo de pentest automatizado para APIs (OWASP ZAP integration)\n• Robótica, IoT & Automação: sensor IoT que monitora ambiente físico e alerta via MQTT\n• Forense Digital: módulo de análise de logs com timeline reconstruction e IOC detection",
    deliverable: "Plataforma em K8s: pipeline RAG, modelo de anomalias, ETL com dbt, smart contract, pentest module, sensor IoT, forense de logs, CI/CD com SAST/DAST"
  }
};

FINAL_LEVEL["red"] = {
  project: {
    title: "🏆 Projeto Final do Muito Avançado: Plataforma Forense com IA Distribuída",
    desc: "Construa plataforma de investigação forense digital potencializada por IA que integra TODAS as 4 áreas:\n\n• Sistemas Distribuídos: Cluster de 3+ nós com consenso Raft para armazenar evidências de forma imutável e consistente. Consistent hashing para distribuir artifacts entre nós. Tolerância a falhas: perder 1 nó não perde dados.\n\n• MLOps & Produção: Pipeline ML que classifica automaticamente artefatos (malware vs benign, tipo de ataque). Model registry com MLflow, monitoramento de drift (artefatos mudam ao longo do tempo), feature store para IOCs extraídos. A/B testing entre modelos de classificação.\n\n• Pesquisa & Fronteira: Modelo multimodal que analisa tanto texto (logs) quanto imagens (screenshots de RAM dumps) para detectar anomalias. RAG com papers de segurança para assistente de pesquisa do investigador. Quantum-resistant hashing para chain of custody futura.\n\n• Ethical Hacking & Forense: Ingestão de evidências (disk images, memory dumps, PCAPs, logs). Análise automatizada: Volatility para memória, file carving para disco, timeline unificada. Dashboard forense com visualização de kill chain. Relatório automatizado com chain of custody.",
    deliverable: "Sistema distribuído de 3+ nós com pipeline forense automatizado, classificador ML de artefatos com MLflow, assistente RAG, análise de disco/memória/rede, dashboard de kill chain, relatório auto-gerado e documentação completa"
  }
};

FINAL_LEVEL["blue"] = {
  project: {
    title: "🏆 Projeto Final da Academia: Mini Paper de Pesquisa Original",
    desc: "Projeto acadêmico completo integrando as 5 áreas:\n\n• Escrita e Metodologia Científica: paper completo em LaTeX (introdução, related work, metodologia, experimentos, conclusão) seguindo template de conferência (ACM/IEEE)\n• Iniciação Científica: proposta de IC formal com problema, justificativa, objetivos SMART, metodologia, cronograma Gantt de 12 meses, orçamento\n• Mestrado: plano de pesquisa de mestrado com revisão bibliográfica de 20+ papers, gap identificado, contribuição esperada\n• Doutorado: survey de uma subárea (10+ papers), análise crítica comparativa, identificação de problemas abertos\n• Ferramentas e Recursos Acadêmicos: projeto reproduzível com Jupyter + seeds fixos + requirements.txt + MLflow tracking + dados versionados com DVC + Binder configurado",
    deliverable: "Paper LaTeX, proposta IC, plano de mestrado, survey com 10+ papers, repositório reproduzível com Binder, MLflow e DVC"
  }
};

FINAL_LEVEL["purple"] = {
  project: {
    title: "🏆 Projeto Final de Carreira: Plano de Carreira de 5 Anos + Contribuição à Comunidade",
    desc: "Plano de carreira integrando as 7 áreas:\n\n• Aprendizado & Preparação de Carreira: auto-avaliação T-shape, plano de estudo 12 meses com spaced repetition, portfolio GitHub com 5+ projetos\n• Trilhas, Crescimento & Transições: mapear 3 trilhas, roadmap 5 anos com milestones, entrevistar profissionais\n• Liderança & Gestão: definir DORA metrics para projetos, sprint planning, postmortem blameless de incidente simulado\n• Liderança Técnica: escrever 3 ADRs, criar runbook operacional, tech spec completa de feature, mentoria documentada\n• Produto & Estratégia: discovery com 5 usuários, wireframes, North Star Metric, priorização RICE\n• Gestão de Pessoas: framework de feedback SBI, plano de onboarding 30/60/90 dias, 1:1 template\n• Estratégia, Negócio & Empreendedorismo: Business Model Canvas, análise TAM/SAM/SOM, pitch deck 10 slides",
    deliverable: "Documento: T-shape, roadmap 5 anos, 3 ADRs, runbook, tech spec, postmortem, discovery, pitch deck, framework feedback, plano onboarding"
  }
};

QUIZZES["__FINAL_GREEN__"] = [
{q:"O que 'clock' de 3.5 GHz em um processador significa?",o:["Consome 3.5 watts — mas na prática funciona de maneira distinta","3.5 bilhões de ciclos por segundo","Tem 3.5 bilhões de transistores","3.5 milhões de instruções por segundo"],a:1},
{q:"Qual técnica de debugging envolve explicar o problema em voz alta para encontrar a solução?",o:["Log analysis — embora relacionado, não é a resposta certa","Step-through debugging","Rubber duck debugging","Print debugging — mas isso descreve outro mecanismo"],a:2},
{q:"O que o comando 'find / -name \"*.log\"' faz?",o:["Comprime logs — mas não é a resposta correta neste caso","Lista diretórios — esse conceito se aplica em outro contexto","Deleta todos os .log — apesar de relacionado, não é o que foi perguntado","Busca todos os arquivos .log a partir da raiz"],a:3},
{q:"O que é swap no contexto de sistemas operacionais?",o:["Tipo de partição — essa seria a resposta para outra pergunta","Backup automático — termo correto mas com significado diferente aqui","Área do disco usada quando a RAM está cheia","Trocar dois processos — embora pareça correto, a definição é outra"],a:2},
{q:"O que o operador walrus (:=) faz em Python?",o:["Compara e atribui — mas não é a resposta correta neste caso","Atribui valor a uma variável dentro de uma expressão","É um smiley — apesar de relacionado, não é o que foi perguntado","Cria constante — funciona diferente do que o enunciado descreve"],a:1},
{q:"O que filter(func, iterable) retorna?",o:["Elementos para os quais func retorna True","Remove duplicatas — termo correto mas com significado diferente aqui","Transforma cada elemento — embora relacionado, não é a resposta certa","Ordena elementos — embora pareça correto, a definição é outra"],a:0},
{q:"O que frozenset é em Python?",o:["Set vazio — mas não é a resposta correta neste caso","Set ordenado — esse conceito se aplica em outro contexto","Set congelado na memória — no entanto isso confunde com outra definição","Set imutável que pode ser chave de dicionário"],a:3},
{q:"O que o Princípio do Pombal (Pigeonhole) afirma?",o:["Pombos voam — essa seria a resposta para outra pergunta","Todos os grafos são conexos — termo correto mas com significado diferente aqui","Se n+1 objetos vão em n caixas, pelo menos uma caixa tem 2+","Toda função é injetora — embora pareça correto, a definição é outra"],a:2},
{q:"O que f''(x) > 0 indica sobre o gráfico de f?",o:["Função crescente","Concavidade para cima","Ponto de inflexão","Concavidade para baixo"],a:1},
{q:"O que eliminação de Gauss resolve?",o:["Sistemas de equações lineares","Equações diferenciais","Derivadas — esse é um conceito diferente em computação","Integrais — embora pareça correto, a definição é outra"],a:0},
{q:"O que o Princípio de Arquimedes afirma?",o:["Fluidos são incompressíveis — mas isso descreve outro conceito diferente","Pressão é constante em fluidos — mas isso descreve outro conceito diferente","Toda matéria é feita de átomos — no entanto isso confunde com outra definição","O empuxo é igual ao peso do fluido deslocado"],a:3},
{q:"O que significa dopagem tipo N em semicondutor?",o:["Remover átomos — essa seria a resposta para outra pergunta","Adicionar buracos — termo correto mas com significado diferente aqui","Adicionar elétrons extras com impurezas doadoras como fósforo","Aquecer o material — embora pareça correto, a definição é outra"],a:2},
{q:"O que optional chaining (?.) faz em JavaScript?",o:["Cria condição — mas não é a resposta correta neste caso","Acessa propriedade sem erro se anterior for null/undefined","Cria optional — apesar de relacionado, não é o que foi perguntado","Encadeia promises — funciona diferente do que o enunciado descreve"],a:1},
{q:"O que 'git bisect' faz?",o:["Busca binária no histórico para encontrar qual commit introduziu um bug","Comprime commits — termo correto mas com significado diferente aqui","Bisecta branches — esse é um conceito diferente em computação","Divide o repositório — embora pareça correto, a definição é outra"],a:0},
{q:"O que 'position: sticky' faz em CSS?",o:["Centraliza o elemento — mas não é a resposta correta neste caso","Fixa o elemento no viewport sempre — esse conceito se aplica em outro contexto","Remove do fluxo — apesar de relacionado, não é o que foi perguntado","Elemento se comporta como relative até scroll atingir, então vira fixed"],a:3},
{q:"O que 'desnormalizar' um banco significa?",o:["Normalizar de novo — essa seria a resposta para outra pergunta","Corrigir erros — termo correto mas com significado diferente aqui","Adicionar redundância intencionalmente para melhorar performance de leitura","Remover tabelas — embora pareça correto, a definição é outra"],a:2},
{q:"Qual é a diferença entre DELETE e TRUNCATE em SQL?",o:["São iguais — esse conceito se aplica em outro contexto","TRUNCATE é mais lento — apesar de relacionado, não é o que foi perguntado","DELETE remove a tabela — funciona diferente do que o enunciado descreve","DELETE pode ter WHERE e é logado; TRUNCATE remove tudo rapidamente"],a:3},
{q:"Qual é a diferença entre Mealy e Moore em máquinas de estados?",o:["São iguais — essa seria a resposta para outra pergunta","Mealy usa menos memória — termo correto mas com significado diferente aqui","Mealy: saída depende de estado + entrada; Moore: saída depende só do estado","Moore é mais rápido — esse é um conceito diferente em computação"],a:2},
{q:"O que um PLL (Phase-Locked Loop) faz?",o:["Mede temperatura — mas não é a resposta correta neste caso","Filtra DC — esse conceito se aplica em outro contexto","Amplifica fase — apesar de relacionado, não é o que foi perguntado","Sincroniza frequência de saída com referência, gerando frequências precisas"],a:3},
{q:"Em qual ordem você deveria aprender: Python, Estruturas de Dados, ou Machine Learning?",o:["Python → ED → ML","Qualquer ordem","ED → Python → ML","ML → ED → Python"],a:0}
];

QUIZZES["__FINAL_YELLOW__"] = [
{q:"Qual é a complexidade de busca em uma árvore binária de busca balanceada?",o:["Relacionado mas não é a definição correta","Termo válido em outro contexto — porém isso pertence a um contexto diferente","Conceito diferente do que está sendo perguntado","O(log n) (resposta correta para esta pergunta)"],a:3},
{q:"O que o padrão Iterator implementa em Python (__iter__ e __next__)?",o:["Protocolo para percorrer coleção sem expor estrutura interna","Filtering — termo correto mas com significado diferente aqui","Loop fixo — esse é um conceito diferente em computação","Sorting — embora pareça correto, a definição é outra"],a:0},
{q:"O que dangling pointer é em C?",o:["Ponteiro para stack — mas não é a resposta correta neste caso","Ponteiro para NULL — esse conceito se aplica em outro contexto","Ponteiro constante — funciona diferente do que o enunciado descreve","Ponteiro que aponta para memória já liberada (free'd)"],a:3},
{q:"O que JIT compilation faz na JVM?",o:["Otimiza garbage collection — essa seria a resposta para outra pergunta","Compila antes de executar — termo correto mas com significado diferente aqui","Compila bytecode frequente para código nativo em runtime, melhorando performance","Interpreta bytecode linha a linha — embora pareça correto, a definição é outra"],a:2},
{q:"Quais são as 4 condições necessárias para deadlock (Coffman)?",o:["Mutex, semáforo, monitor, barrier — no entanto isso confunde com outra definição","FCFS, SJF, RR, Priority — esse conceito se aplica em outro contexto","Race condition, starvation, thrashing, paging","Exclusão mútua, posse e espera, sem preempção, espera circular"],a:3},
{q:"O que forwarding/bypassing resolve em pipeline de CPU?",o:["Data hazards: encaminha resultado sem esperar writeback","Structural hazards — termo correto mas com significado diferente aqui","Cache misses — esse é um conceito diferente em computação","Hazards de controle — embora pareça correto, a definição é outra"],a:0},
{q:"O que a Lei de Amdahl limita?",o:["Memória máxima — mas não é a resposta correta neste caso","Tamanho do programa — esse conceito se aplica em outro contexto","Número de threads — apesar de relacionado, não é o que foi perguntado","Speedup máximo: limitado pela fração serial do programa"],a:3},
{q:"O que o princípio Open/Closed (SOLID) diz?",o:["Classes devem ser abertas — embora relacionado, não é a resposta certa","Classes nunca mudam — termo correto mas com significado diferente aqui","Aberto para extensão, fechado para modificação","Aberto e fechado ao mesmo tempo — embora relacionado, não é a resposta certa"],a:2},
{q:"O que o Halting Problem prova?",o:["P = NP — mas não é a resposta correta neste caso","Existe problema que nenhum algoritmo pode resolver (indecidível)","Programas sempre terminam — apesar de relacionado, não é o que foi perguntado","Compiladores são perfeitos — funciona diferente do que o enunciado descreve"],a:1},
{q:"O que o gradiente descendente minimiza?",o:["A função de custo/loss atualizando parâmetros na direção oposta ao gradiente","Dados — termo correto mas com significado diferente aqui","Número de features — esse é um conceito diferente em computação","Variância — embora pareça correto, a definição é outra"],a:0},
{q:"Por que o Teorema de Nyquist é essencial para digitalizar sinais?",o:["Comprime dados — mas não é a resposta correta neste caso","Reduz ruído — esse conceito se aplica em outro contexto","Define que amostragem deve ser ≥ 2× frequência máxima para evitar aliasing","Melhora qualidade — apesar de relacionado, não é o que foi perguntado"],a:2},
{q:"O que N+1 query problem é em aplicações full-stack?",o:["Erro de SQL — mas esse comportamento não corresponde ao real","Query lenta — termo correto mas com significado diferente aqui","Para cada item de uma lista, fazer query separada ao banco (deveria ser JOIN/batch)","Problema de cache — embora pareça correto, a definição é outra"],a:2},
{q:"Por que Go é popular para microsserviços e ferramentas cloud-native?",o:["É orientada a objetos — mas não é a resposta correta neste caso","É a mais antiga — apesar de relacionado, não é o que foi perguntado","Tem mais bibliotecas — funciona diferente do que o enunciado descreve","Binário estático, concorrência nativa (goroutines), startup rápido, baixo uso de memória"],a:3},
{q:"O que acontece se W+R ≤ N em subnetting: quantos hosts uma rede /25 suporta?",o:["126 hosts utilizáveis (128 menos rede e broadcast)","Conceito diferente do que foi perguntado","128 — esse é um conceito diferente em computação","256 — embora pareça correto, a definição é outra"],a:0},
{q:"O que SQL injection explora?",o:["Bugs de CSS — mas não é a resposta correta neste caso","Buffer overflow — esse conceito se aplica em outro contexto","XSS — apesar de relacionado, não é o que foi perguntado","Input não sanitizado que permite executar SQL malicioso no banco"],a:3},
{q:"O que Rate Monotonic scheduling garante em RTOS?",o:["Menor latência — essa seria a resposta para outra pergunta","Fairness — termo correto mas com significado diferente aqui","Task com menor período recebe maior prioridade","Round-robin — embora pareça correto, a definição é outra"],a:2},
{q:"Em um sistema Full-Stack com Docker, qual a ordem correta de inicialização?",o:["Frontend → Backend → Banco — mas não é a resposta correta neste caso","Tudo junto — esse conceito se aplica em outro contexto","Não importa a ordem — apesar de relacionado, não é o que foi perguntado","Banco → Backend → Frontend (dependências de baixo para cima)"],a:3},
{q:"O que é o zero value em Go e por que é importante?",o:["Toda variável tem valor padrão sem inicializar (0, '', nil, false) — evita undefined behavior","Constante zero — no entanto esse é um equívoco frequente","Erro de inicialização — termo correto mas com significado diferente aqui","Valor nulo como null — porém isso pertence a um contexto diferente"],a:0},
{q:"O que rasterização faz na pipeline gráfica?",o:["Aplica filtro — mas não é a resposta correta neste caso","Comprime imagem — esse conceito se aplica em outro contexto","Vetoriza imagem — apesar de relacionado, não é o que foi perguntado","Converte primitivas geométricas (triângulos) em pixels na tela"],a:3},
{q:"O que a tríade CIA em segurança da informação representa?",o:["Agência dos EUA — termo correto mas com significado diferente aqui","Certificado, ID, Acesso — esse é um conceito diferente em computação","Confidencialidade, Integridade e Disponibilidade (Availability)","Criptografia, Identificação, Autorização — mas esse comportamento não corresponde ao real"],a:2}
];

QUIZZES["__FINAL_ORANGE__"] = [
{q:"O que acontece se um microsserviço falha em um sistema com circuit breaker?",o:["Sistema todo cai — mas não é a resposta correta neste caso","Circuit breaker abre, retorna fallback e tenta reconectar depois (fail gracefully)","Ignora a falha — apesar de relacionado, não é o que foi perguntado","Reinicia todo o cluster — funciona diferente do que o enunciado descreve"],a:1},
{q:"O que attention scores em um Transformer representam?",o:["Quanto cada token deve 'prestar atenção' a cada outro token na sequência","Notas de prova — termo correto mas com significado diferente aqui","Velocidade de treino — esse é um conceito diferente em computação","Tamanho do modelo — embora pareça correto, a definição é outra"],a:0},
{q:"O que é chunk overlap em RAG e por que é importante?",o:["Erro de indexação — mas não é a resposta correta neste caso","Tipo de compressão — esse conceito se aplica em outro contexto","Duplicação de dados — apesar de relacionado, não é o que foi perguntado","Sobreposição entre chunks garante que contexto não é cortado na fronteira"],a:3},
{q:"O que é variant calling em genômica?",o:["Tipo de alinhamento — essa seria a resposta para outra pergunta","Ligar para variantes — termo correto mas com significado diferente aqui","Identificar diferenças (SNPs, indels) entre sequência amostrada e genoma de referência","Sequenciamento — embora relacionado, não é a resposta certa"],a:2},
{q:"Quando usar Redis vs PostgreSQL para um dado específico?",o:["Sempre Redis — embora pareça plausível, não se aplica neste caso","Sempre PostgreSQL — no entanto confunde-se frequentemente com outro termo relacionado","São intercambiáveis — que é um mecanismo distinto e não corresponde ao comportamento descrito","Redis para dados temporários/cache com acesso ultrarrápido; PostgreSQL para dados persistentes e relacionais"],a:3},
{q:"O que é idempotência em pipelines de dados e por que importa?",o:["Re-executar pipeline produz mesmo resultado","Schema evolution — essa seria a resposta para outra pergunta","Tipo de transformação — esse é um conceito diferente em computação","Performance — embora pareça correto, a definição é outra"],a:0},
{q:"O que é o trilema da blockchain (escalabilidade, segurança, descentralização)?",o:["Só importa segurança — mas não é a resposta correta neste caso","São independentes — esse conceito se aplica em outro contexto","Resolvido — apesar de relacionado, não é o que foi perguntado","É difícil otimizar os 3 simultaneamente: melhorar um geralmente compromete outro"],a:3},
{q:"O que é o difference entre Deployment e StatefulSet no Kubernetes?",o:["Deployment é mais novo — embora relacionado, não é a resposta certa","São iguais — mas na prática isso descreve um processo completamente diferente","Deployment: pods intercambiáveis; StatefulSet: identidade estável, storage persistente por pod (bancos)","StatefulSet é deprecated — porém essa definição pertence a outro conceito da mesma área"],a:2},
{q:"O que é a diferença entre SAST e DAST?",o:["DAST substitui SAST — mas não é a resposta correta neste caso","SAST analisa código estático (source code); DAST testa aplicação rodando (black-box)","São iguais — apesar de relacionado, não é o que foi perguntado","SAST é mais completo — funciona diferente do que o enunciado descreve"],a:1},
{q:"O que é IDOR (Insecure Direct Object Reference)?",o:["Acessar recursos de outros usuários manipulando ID no request","Buffer overflow — termo correto mas com significado diferente aqui","Tipo de link — esse é um conceito diferente em computação","Tipo de XSS — embora pareça correto, a definição é outra"],a:0},
{q:"O que é o loop perception-planning-action em robótica?",o:["Tipo de SLAM — no entanto isso confunde com outra definição","Tipo de PID — embora pareça plausível, não se aplica neste caso","Loop infinito — apesar de relacionado, não é o que foi perguntado","Ciclo contínuo: perceber ambiente → planejar ação → executar → perceber resultado → repetir"],a:3},
{q:"Por que event-driven architecture é melhor que REST síncrono para microsserviços desacoplados?",o:["São iguais — embora seja um erro comum, não é o que acontece neste cenário","Serviços não esperam resposta; comunicação assíncrona permite escalabilidade e resiliência independentes","É mais simples — no entanto confunde-se frequentemente com outro termo relacionado","REST é deprecated — mas na prática funciona de maneira distinta"],a:1},
{q:"O que é observability-driven development?",o:["Só monitorar produção — porém isso pertence a um contexto diferente","Instrumentar código com logs, métricas e traces desde o início para entender comportamento em qualquer ambiente","Tipo de TDD — mas na prática isso descreve um processo completamente diferente","Debugging avançado — que é um mecanismo distinto e não corresponde ao comportamento descrito"],a:1},
{q:"O que é data contract entre serviços?",o:["Tipo de teste — termo correto mas com significado diferente aqui","Contrato jurídico — esse é um conceito diferente em computação","Tipo de API — embora pareça correto, a definição é outra","Acordo formal sobre schema, formato e SLA dos dados entre produtor e consumidor"],a:3},
{q:"O que é blue-green vs canary deployment?",o:["Canary é instantâneo — mas não é a resposta correta neste caso","São iguais — ainda que comum, essa interpretação está incorreta","Blue-green é gradual — apesar de relacionado, não é o que foi perguntado","Blue-green: troca total instantânea; canary: rollout gradual para percentual de usuários"],a:3},
{q:"Por que container scanning é crítico em CI/CD?",o:["Só para compliance — porém esse não é o mecanismo correto aqui","Opcional — porém isso pertence a um contexto diferente","Imagens podem herdar vulnerabilidades de base images e dependências que entram em produção","Melhora performance — embora pareça correto, a definição é outra"],a:2},
{q:"O que é graceful degradation em sistemas distribuídos?",o:["Desligar serviços — mas não é a resposta correta neste caso","Sistema continua funcionando com funcionalidade reduzida quando componente falha","Tipo de rollback — apesar de relacionado, não é o que foi perguntado","Sistema morre elegantemente — funciona diferente do que o enunciado descreve"],a:1},
{q:"Como IA e edge computing se complementam em IoT industrial?",o:["Edge processa dados localmente (baixa latência), IA infere anomalias sem depender de cloud","Edge substitui IA — porém isso pertence a um contexto diferente","IA substitui edge — porém isso pertence a um contexto diferente","Não se relacionam — no entanto esse é um equívoco frequente"],a:0},
{q:"O que é GitOps e qual é o benefício principal?",o:["Tipo de CI/CD — embora seja um erro comum, não é o que acontece neste cenário","Framework web — no entanto confunde-se frequentemente com outro termo relacionado","Git como backup — embora relacionado, não é a resposta certa","Git como fonte de verdade: infraestrutura declarativa, auditável, versionada e auto-sincronizada"],a:3},
{q:"Por que fine-tuning nem sempre é a melhor abordagem para customizar LLMs?",o:["É sempre a melhor — porém essa definição pertence a outro conceito da mesma área","RAG é mais barato, não precisa de dados de treino, mantém modelo atualizado e evita catastrophic forgetting","Fine-tuning é impossível — termo correto mas com significado diferente aqui","São equivalentes — porém essa definição pertence a outro conceito da mesma área"],a:1}
];

QUIZZES["__FINAL_RED__"] = [
{q:"O que acontece se W+R ≤ N em um sistema de quorum?",o:["Consistência forte — mas não é a resposta correta neste caso","Leituras podem retornar dados desatualizados (consistência eventual, não forte)","Nada muda — apesar de relacionado, não é o que foi perguntado","Sistema falha — funciona diferente do que o enunciado descreve"],a:1},
{q:"Por que CRDTs são preferíveis a locks em sistemas distribuídos de alta disponibilidade?",o:["Locks não existem em distribuídos — termo correto mas com significado diferente aqui","São mais rápidos — embora relacionado, não é a resposta certa","São mais simples — mas isso descreve outro conceito diferente","Convergem automaticamente sem coordenação, evitando latência e indisponibilidade de locks distribuídos"],a:3},
{q:"O que é training-serving skew e como detectar?",o:["Tipo de drift — embora seja um erro comum, não é o que acontece neste cenário","Overfitting — ainda que comum, essa interpretação está incorreta","Bug de GPU — porém essa definição pertence a outro conceito da mesma área","Features computadas diferentemente em treino vs produção; detectar comparando distribuições de features"],a:3},
{q:"Por que feature store é importante em MLOps?",o:["Tipo de banco — porém essa definição pertence a outro conceito da mesma área","Opcional — no entanto confunde-se frequentemente com outro termo relacionado","Garante que features são consistentes entre treino e serving, reutilizáveis entre equipes e versionadas","Armazena modelos — no entanto esse é um equívoco frequente"],a:2},
{q:"O que é reward hacking em RL?",o:["Tipo de exploit — ainda que comum, essa interpretação está incorreta","Agente encontra forma de maximizar reward sem realmente resolver o problema intencionado","Bug de código — apesar de relacionado, não é o que foi perguntado","Hackear recompensas — funciona diferente do que o enunciado descreve"],a:1},
{q:"Por que computação quântica ameaça criptografia RSA?",o:["Não ameaça — termo correto mas com significado diferente aqui","Quantum é mais rápido em tudo — esse é um conceito diferente em computação","Quantum já quebrou RSA — embora pareça correto, a definição é outra","Algoritmo de Shor fatora números grandes eficientemente, quebrando a premissa de RSA"],a:3},
{q:"O que é order of volatility em forense e por que importa?",o:["Não importa a ordem — mas isso descreve outro conceito diferente","Ordem de importância — no entanto isso confunde com outra definição","Ordem alfabética — apesar de relacionado, não é o que foi perguntado","Coletar evidências da mais volátil (RAM, cache) para menos volátil (disco) antes que desapareçam"],a:3},
{q:"O que timestomping é em anti-forensics?",o:["Sincronizar relógio — essa seria a resposta para outra pergunta","Carimbar tempo — termo correto mas com significado diferente aqui","Alterar timestamps de arquivos para confundir timeline analysis e esconder atividade","Tipo de backup — embora pareça correto, a definição é outra"],a:2},
{q:"Como garantir integridade de evidências em um sistema distribuído?",o:["Confiar nos nós — porém isso pertence a um contexto diferente","Hash criptográfico de cada evidência replicado via consenso: qualquer alteração é detectável","Backup suficiente — apesar de relacionado, não é o que foi perguntado","Criptografar tudo — funciona diferente do que o enunciado descreve"],a:1},
{q:"Por que monitoramento de model drift é especialmente crítico em sistemas de detecção de malware?",o:["Malware não muda — termo correto mas com significado diferente aqui","Drift é lento em segurança — esse é um conceito diferente em computação","Não é crítico — no entanto esse é um equívoco frequente","Atacantes evoluem táticas constantemente, então distribuição de inputs muda (adversarial drift)"],a:3},
{q:"O que é Byzantine fault tolerance e quando é necessário?",o:["Nunca necessário — no entanto esse é um equívoco frequente","Sempre necessário — apesar de relacionado, não é o que foi perguntado","Tolerância a bugs — embora pareça plausível, não se aplica neste caso","Consenso mesmo com nós maliciosos; necessário quando nós não são confiáveis (blockchain, militar)"],a:3},
{q:"Como RL pode ser aplicado a incident response automatizado?",o:["Agente aprende política de containment otimizando: minimizar dano, tempo de resposta e falsos positivos","Não pode — mas na prática isso descreve um processo completamente diferente","Só com supervised learning — embora relacionado, não é a resposta certa","Só com regras manuais — embora seja um erro comum, não é o que acontece neste cenário"],a:0},
{q:"O que é post-quantum cryptography?",o:["Criptografia pós-apocalipse — que é um mecanismo distinto e não corresponde ao comportamento descrito","Algoritmos criptográficos resistentes a ataques de computadores quânticos (lattice-based, hash-based)","Tipo de RSA — no entanto confunde-se frequentemente com outro termo relacionado","Criptografia quântica — embora pareça plausível, não se aplica neste caso"],a:1},
{q:"Por que idempotência é crucial em pipelines de MLOps distribuídos?",o:["Tipo de consistência — termo correto mas com significado diferente aqui","Não é importante — porém esse não é o mecanismo correto aqui","Melhora performance — embora relacionado, não é a resposta certa","Re-execuções (retries, crashes) não devem duplicar dados/treinos nem corromper model registry"],a:3},
{q:"O que diferencia forense de memória de forense de disco?",o:["Memória não tem evidências — no entanto esse é um equívoco frequente","São iguais — no entanto confunde-se frequentemente com outro termo relacionado","Disco é mais útil — embora seja um erro comum, não é o que acontece neste cenário","Memória é volátil (desaparece ao desligar) e contém estado em execução: processos, chaves, malware fileless"],a:3},
{q:"Como escalar inferência de modelos ML em sistema distribuído?",o:["Não é possível — mas esse comportamento não corresponde ao real","Load balancing entre réplicas do modelo, batching de requests, model sharding para modelos grandes","Só usar GPU maior — ainda que comum, essa interpretação está incorreta","Só vertical scaling — embora relacionado, não é a resposta certa"],a:1},
{q:"O que é o princípio de Locard em forense digital?",o:["Tipo de hash — mas na prática isso descreve um processo completamente diferente","Todo contato deixa rastro: atacante sempre deixa evidência e sempre leva algo consigo (logs, artifacts)","Lei de Amdahl — no entanto confunde-se frequentemente com outro termo relacionado","Lei de programação — no entanto isso confunde com outra definição"],a:1},
{q:"Qual é o papel de vector clocks em um sistema de log forense distribuído?",o:["Tipo de timestamp — essa seria a resposta para outra pergunta","Não são úteis — termo correto mas com significado diferente aqui","Sincronizar relógios — esse é um conceito diferente em computação","Ordenar eventos causalmente entre nós sem depender de relógios sincronizados"],a:3},
{q:"Por que quantum error correction é o maior desafio prático da computação quântica?",o:["Hardware já resolveu — porém isso pertence a um contexto diferente","É fácil de resolver — mas na prática isso descreve um processo completamente diferente","Qubits são extremamente sensíveis a ruído; correção requer muitos qubits físicos por qubit lógico","Não é desafio — mas na prática isso descreve um processo completamente diferente"],a:2},
{q:"Como combinar threat hunting proativo com ML em um SOC?",o:["ML substitui analistas — mas isso descreve outro conceito diferente","São incompatíveis — embora relacionado, não é a resposta certa","ML detecta anomalias e prioriza alertas; analista humano formula hipóteses e investiga com contexto","Só regras manuais funcionam — embora pareça correto, a definição é outra"],a:2}
];

QUIZZES["__FINAL_BLUE__"] = [
{q:"O que uma boa seção de Related Work deve fazer além de listar papers?",o:["Criticar papers — no entanto esse é um equívoco frequente","Comparar abordagens, identificar gaps e posicionar sua contribuição em relação ao estado da arte","Só listar — ainda que comum, essa interpretação está incorreta","Citar todos os papers existentes — funciona diferente do que o enunciado descreve"],a:1},
{q:"Por que reprodutibilidade é um pilar fundamental da ciência?",o:["Só para exatas — que é um mecanismo distinto e não corresponde ao comportamento descrito","É opcional — embora seja um erro comum, não é o que acontece neste cenário","Não é importante em CS — porém esse não é o mecanismo correto aqui","Permite verificar resultados independentemente; sem ela, descobertas não podem ser validadas pela comunidade"],a:3},
{q:"O que diferencia uma boa pergunta de pesquisa de uma pergunta vaga?",o:["Tamanho da pergunta — mas não é a resposta correta neste caso","Precisa ser ampla — esse conceito se aplica em outro contexto","Qualquer pergunta serve — apesar de relacionado, não é o que foi perguntado","Boa pergunta é específica, testável, relevante e delimitada em escopo"],a:3},
{q:"Por que é importante fazer revisão de literatura ANTES de começar experimentos?",o:["Só após resultados — essa seria a resposta para outra pergunta","Para encher o paper — termo correto mas com significado diferente aqui","Para não reinventar a roda, entender estado da arte e refinar hipóteses e metodologia","Não é importante — embora pareça correto, a definição é outra"],a:2},
{q:"O que uma contribuição de mestrado deve demonstrar?",o:["Descoberta revolucionária — mas não é a resposta correta neste caso","Capacidade de conduzir pesquisa independente com rigor metodológico e contribuição incremental","Muitas publicações — apesar de relacionado, não é o que foi perguntado","Código perfeito — mas na prática funciona de maneira distinta"],a:1},
{q:"Qual é o papel do orientador vs do mestrando?",o:["Mestrando é independente desde o dia 1 — essa seria a resposta para outra pergunta","Orientador faz tudo — termo correto mas com significado diferente aqui","Orientador guia com experiência e feedback; mestrando executa pesquisa com autonomia crescente","Orientador só assina — mas na prática funciona de maneira distinta"],a:2},
{q:"O que é originalidade em uma tese de doutorado?",o:["Mais dados — mas na prática isso descreve um processo completamente diferente","Tema diferente — que é um mecanismo distinto e não corresponde ao comportamento descrito","Nunca feito antes — no entanto isso confunde com outra definição","Contribuição substancial e inédita: novo método, novo framework, nova teoria ou nova evidência significativa"],a:3},
{q:"O que é impact factor e por que não é a única métrica relevante?",o:["Não existe — embora seja um erro comum, não é o que acontece neste cenário","Métrica perfeita — que é um mecanismo distinto e não corresponde ao comportamento descrito","Mede citações do periódico, não do paper individual; qualidade da contribuição e citações individuais também importam","É a única que importa — porém isso pertence a um contexto diferente"],a:2},
{q:"Por que Docker é importante para reprodutibilidade científica?",o:["Empacota ambiente completo (OS, dependências, versões) para que experimento rode identicamente em qualquer máquina","Só para deploy — no entanto confunde-se frequentemente com outro termo relacionado","Moda de DevOps — mas na prática isso descreve um processo completamente diferente","Melhora performance — mas isso descreve outro conceito diferente"],a:0},
{q:"O que Zotero/Mendeley resolvem que BibTeX manual não resolve bem?",o:["Gerenciamento automático de PDFs, metadados, citações em múltiplos estilos e sincronização entre dispositivos","BibTeX é melhor — porém isso pertence a um contexto diferente","Nada — que é um mecanismo distinto e não corresponde ao comportamento descrito","São iguais — no entanto confunde-se frequentemente com outro termo relacionado"],a:0},
{q:"Como a revisão por pares, apesar de imperfeita, protege a ciência?",o:["Deveria ser abolida — embora relacionado, não é a resposta certa","É perfeita — que é um mecanismo distinto e não corresponde ao comportamento descrito","Não protege — no entanto confunde-se frequentemente com outro termo relacionado","Filtro de qualidade: especialistas verificam validade, metodologia e contribuição antes de publicação"],a:3},
{q:"Qual é a relação entre IC, mestrado e doutorado na formação de pesquisador?",o:["Progressão: IC desenvolve habilidades básicas de pesquisa, mestrado aprofunda, doutorado cria contribuição original","Só doutorado importa — porém essa definição pertence a outro conceito da mesma área","São independentes — embora pareça plausível, não se aplica neste caso","IC substitui mestrado — porém essa definição pertence a outro conceito da mesma área"],a:0},
{q:"Por que open access é um debate importante na ciência?",o:["Conhecimento financiado publicamente deveria ser acessível a todos, mas editoras lucram com paywalls","Open access é pior — mas na prática funciona de maneira distinta","Já foi resolvido — que é um mecanismo distinto e não corresponde ao comportamento descrito","Não é importante — que é um mecanismo distinto e não corresponde ao comportamento descrito"],a:0},
{q:"O que um pipeline de pesquisa reproduzível deve conter?",o:["Só os resultados — que é um mecanismo distinto e não corresponde ao comportamento descrito","Só o paper — porém essa definição pertence a outro conceito da mesma área","Só o código — no entanto isso confunde com outra definição","Código versionado + dados (ou link) + ambiente (Docker/conda) + instruções claras + automatização (Make/DVC)"],a:3},
{q:"Por que escrever bem é tão importante quanto pesquisar bem?",o:["Escrita é secundária — porém esse não é o mecanismo correto aqui","Código é suficiente — esse conceito se aplica em outro contexto","Pesquisa que não é comunicada claramente não impacta; escrita é o veículo da contribuição","Não é importante — apesar de relacionado, não é o que foi perguntado"],a:2},
{q:"Qual é o papel de conferências vs periódicos em Computação?",o:["Conferências são venues primárias em CS (rápidas, peer-reviewed, competitivas); periódicos são mais detalhados","Periódicos são melhores — mas na prática isso descreve um processo completamente diferente","São iguais — porém essa definição pertence a outro conceito da mesma área","Conferências são informais — embora pareça plausível, não se aplica neste caso"],a:0},
{q:"Como IA e ferramentas como LLMs estão mudando a pesquisa acadêmica?",o:["Substituem pesquisadores — no entanto esse é um equívoco frequente","Auxiliam em revisão de literatura, escrita e análise, mas levantam questões de autoria e integridade","São proibidos — no entanto confunde-se frequentemente com outro termo relacionado","Não têm impacto — mas na prática isso descreve um processo completamente diferente"],a:1},
{q:"O que é ética em pesquisa computacional?",o:["Considerar impacto social, viés em dados, privacidade, reprodutibilidade e uso responsável de resultados","Não existe em CS — embora pareça plausível, não se aplica neste caso","Só para biomédica — que é um mecanismo distinto e não corresponde ao comportamento descrito","Só seguir a lei — mas na prática isso descreve um processo completamente diferente"],a:0},
{q:"Por que manter Lattes e ORCID atualizados é importante para pesquisadores brasileiros?",o:["Burocracia desnecessária — no entanto esse é um equívoco frequente","Ninguém confere — embora relacionado, não é a resposta certa","São usados em avaliações de bolsas, concursos e financiamento; ORCID integra internacionalmente","Só Lattes importa — apesar de relacionado, não é o que foi perguntado"],a:2},
{q:"O que é revisão sistemática de literatura e quando usar?",o:["Revisão narrativa é melhor — embora pareça plausível, não se aplica neste caso","Só para doutorado — que é um mecanismo distinto e não corresponde ao comportamento descrito","Busca estruturada e reproduzível com protocolo definido; usar quando se quer mapear estado da arte rigorosamente","Ler papers aleatórios — porém essa definição pertence a outro conceito da mesma área"],a:2}
];

QUIZZES["__FINAL_PURPLE__"] = [
{q:"Por que aprender a aprender é a habilidade mais importante em tech?",o:["Tecnologias mudam rápido; quem aprende eficientemente se adapta; meta-learning > qualquer tecnologia específica","Experiência é tudo — porém essa definição pertence a outro conceito da mesma área","Só saber programar basta — no entanto isso confunde com outra definição","Não é — no entanto confunde-se frequentemente com outro termo relacionado"],a:0},
{q:"O que é a diferença entre IC track e management track?",o:["IC: crescer em profundidade técnica e impacto (Staff, Principal); management: crescer liderando pessoas e times","IC é melhor — no entanto confunde-se frequentemente com outro termo relacionado","São iguais — porém essa definição pertence a outro conceito da mesma área","Management é melhor — mas esse comportamento não corresponde ao real"],a:0},
{q:"O que são DORA metrics e por que são melhores que linhas de código?",o:["Métricas de código — mas esse comportamento não corresponde ao real","Medem eficácia de entrega (deploy frequency, lead time, failure rate, recovery); LOC não mede valor","LOC é mais preciso — que é um mecanismo distinto e não corresponde ao comportamento descrito","São iguais — mas na prática isso descreve um processo completamente diferente"],a:1},
{q:"O que é a diferença entre urgente e importante na priorização?",o:["São iguais — embora pareça plausível, não se aplica neste caso","Importante pode esperar sempre — termo correto mas com significado diferente aqui","Urgente precisa de ação imediata; importante contribui para objetivos de longo prazo (Eisenhower matrix)","Urgente é mais importante — embora pareça plausível, não se aplica neste caso"],a:2},
{q:"Por que documentar decisões técnicas (ADRs) é mais valioso que documentar código?",o:["ADRs capturam O PORQUÊ de decisões; código mostra O QUÊ; contexto perdido é irrecuperável","Código documenta sozinho — mas não é a resposta correta neste caso","ADRs são burocráticos — apesar de relacionado, não é o que foi perguntado","Não é — embora relacionado, não é a resposta certa"],a:0},
{q:"O que é a diferença entre on-call saudável e on-call tóxico?",o:["Saudável: runbooks, rotação justa, baixo volume de alertas; tóxico: alertas constantes, sem documentação, sem rotação","On-call é opcional — mas na prática isso descreve um processo completamente diferente","São iguais — mas na prática isso descreve um processo completamente diferente","On-call é sempre tóxico — mas esse comportamento não corresponde ao real"],a:0},
{q:"Por que falar com usuários é mais valioso que intuição para decisões de produto?",o:["São igualmente valiosos — mas na prática funciona de maneira distinta","Usuários não sabem o que querem — esse conceito se aplica em outro contexto","Intuição basta — embora pareça plausível, não se aplica neste caso","Usuários revelam problemas reais que devs não antecipam; dados > opinião para validar hipóteses"],a:3},
{q:"O que é a diferença entre output e outcome em produto?",o:["Output é mais importante — ainda que comum, essa interpretação está incorreta","São iguais — mas na prática isso descreve um processo completamente diferente","Output: features entregues (o que fizemos); outcome: impacto no usuário/negócio (o que conseguimos)","Outcome é imensurável — que é um mecanismo distinto e não corresponde ao comportamento descrito"],a:2},
{q:"O que é psychological safety e por que é o fator #1 de times de alta performance?",o:["Conforto sem desafio — embora seja um erro comum, não é o que acontece neste cenário","Segurança para correr riscos e discordar sem medo; Google Project Aristotle mostrou ser o preditor mais forte","Não é comprovado — porém essa definição pertence a outro conceito da mesma área","Skill individual é mais importante — funciona diferente do que o enunciado descreve"],a:1},
{q:"Por que feedback frequente é melhor que review anual?",o:["Review anual é mais justo — termo correto mas com significado diferente aqui","Feedback cansa pessoas — esse é um conceito diferente em computação","Não é melhor — no entanto esse é um equívoco frequente","Curso-correção rápida, comportamento ainda é recente, menos surpresas, crescimento contínuo"],a:3},
{q:"O que é moat (fosso competitivo) e por que importa para engenheiros?",o:["Só para executivos — no entanto esse é um equívoco frequente","Moat é só marketing — mas esse comportamento não corresponde ao real","Não é relevante para devs — apesar de relacionado, não é o que foi perguntado","Engenheiro que entende moat toma melhores decisões técnicas: o que construir, como diferenciar"],a:3},
{q:"O que é a relação entre velocidade de entrega e qualidade?",o:["A longo prazo são complementares: qualidade (testes, CI/CD, good code) ACELERA entrega sustentável","Velocidade > qualidade — embora seja um erro comum, não é o que acontece neste cenário","Qualidade > velocidade — termo correto mas com significado diferente aqui","São opostos — que é um mecanismo distinto e não corresponde ao comportamento descrito"],a:0},
{q:"O que é a diferença entre carreira e emprego?",o:["Emprego é mais importante — no entanto isso confunde com outra definição","Emprego: posição atual; carreira: trajetória de longo prazo com skills, rede e reputação acumulados","São iguais — no entanto confunde-se frequentemente com outro termo relacionado","Carreira é ficção — porém essa definição pertence a outro conceito da mesma área"],a:1},
{q:"Por que engenheiros devem entender negócio?",o:["É trabalho do PM — termo correto mas com significado diferente aqui","Não devem — mas na prática funciona de maneira distinta","Negócio é para MBAs — mas isso descreve outro conceito diferente","Decisões técnicas impactam negócio; entender contexto permite priorizar o que gera mais valor"],a:3},
{q:"O que é mentoria reversa e por que é valiosa?",o:["Senior sabe tudo — porém isso pertence a um contexto diferente","É desrespeitoso — esse conceito se aplica em outro contexto","Não existe — apesar de relacionado, não é o que foi perguntado","Pessoa mais junior mentorea senior em novas tecnologias/perspectivas; ambos aprendem"],a:3},
{q:"Como equilíbrio entre habilidades técnicas e soft skills evolui com senioridade?",o:["Soft skills não importam — mas esse comportamento não corresponde ao real","Mais senior = mais soft skills (comunicação, influência, visão); técnico continua mas proporção muda","São sempre 50/50 — porém essa definição pertence a outro conceito da mesma área","Técnico sempre domina — mas na prática isso descreve um processo completamente diferente"],a:1},
{q:"O que é compound learning (aprendizado composto)?",o:["Estudar muito rápido — esse conceito se aplica em outro contexto","Habilidades se acumulam e reforçam mutuamente ao longo do tempo, como juros compostos","Tipo de spaced repetition — apesar de relacionado, não é o que foi perguntado","Aprender tudo de uma vez — funciona diferente do que o enunciado descreve"],a:1},
{q:"Por que contribuir para open source é bom para carreira?",o:["Só beneficia a empresa — termo correto mas com significado diferente aqui","Não é valorizado — mas na prática isso descreve um processo completamente diferente","Demonstra habilidade publicamente, expande rede, aprende com code review de experts, constrói reputação","Trabalho de graça — embora seja um erro comum, não é o que acontece neste cenário"],a:2},
{q:"O que é a diferença entre liderar e gerenciar?",o:["Liderar é melhor — embora seja um erro comum, não é o que acontece neste cenário","São iguais — no entanto confunde-se frequentemente com outro termo relacionado","Gerenciar é mais útil — apesar de relacionado, não é o que foi perguntado","Liderar: definir direção, inspirar, inovar; gerenciar: organizar, planejar, executar (ambos necessários)"],a:3},
{q:"O que é North Star Metric e por que todo produto precisa de uma?",o:["Métrica de astronomia — termo correto mas com significado diferente aqui","Número de usuários sempre — esse é um conceito diferente em computação","Uma métrica que melhor captura o valor entregue aos usuários e guia toda a estratégia do produto","Revenue sempre — embora relacionado, não é a resposta certa"],a:2}
];

